import type { SeoLandingPage } from './types';

export const deDriverPage: SeoLandingPage = {
  locale: 'de',
  slug: 'albanien-rundreise-mit-fahrer',
  metaTitle: 'Albanien-Rundreise mit privatem Fahrer | Arjes',
  metaDescription: 'Private Albanien-Rundreise mit Fahrer, auf Wunsch mit deutschsprachigem Guide. Individuelle Route, passendes Fahrzeug und transparente Tagesplanung.',
  ogTitle: 'Albanien privat mit Fahrer bereisen',
  breadcrumb: 'Albanien-Rundreise mit Fahrer',
  serviceName: 'Private Albanien-Rundreise mit Fahrer',
  serviceTypes: ['Privater Fahrer Albanien', 'Albanien Rundreise mit Fahrer', 'Fahrer und Reiseleitung Albanien'],
  audience: 'Paare, Familien und private Gruppen, die Albanien ohne eigenes Fahren bereisen möchten',
  nav: { options: 'Reisearten', ideas: 'Routen', details: 'Leistungen', questions: 'Fragen' },
  headerCta: 'Fahrer anfragen',
  hero: {
    eyebrow: 'Privater Fahrer · individuelle Route · Albanien',
    title: 'Sie schauen aus dem Fenster. Jemand anderes denkt an die Straße.',
    lede: 'Eine private Rundreise mit Fahrer nimmt Ihnen Navigation, Parkplätze und tägliche Fahrzeuglogistik ab. Ergänzen Sie einen deutschsprachigen Guide für die ganze Reise oder nur dort, wo Einordnung und Gespräche den Unterschied machen.',
    primaryCta: 'Route mit Fahrer anfragen',
    secondaryCta: 'Reisearten vergleichen',
    facts: ['Privat für Ihre Gruppe', 'Fahrzeug passend zu Gepäck und Route', 'Guide optional'],
    image: '/photos/vjosa.jpeg',
    imageAlt: 'Straßennahe Aussicht auf den Fluss Vjosa und Berge in Südalbanien',
    imageCaption: 'Vjosa-Tal · der Weg gehört zur Reise',
    note: 'Ein Fahrer spart nicht nur Arbeit. Er gibt der ganzen Gruppe die Freiheit, unterwegs gemeinsam zu schauen, zu reden oder einfach nichts zu tun.',
  },
  promise: {
    label: 'Fahrer ist nicht automatisch Guide',
    title: 'Zwei Rollen, die man bewusst kombinieren sollte.',
    body: 'Ein sorgfältiger Fahrer bringt Sie sicher und pünktlich durch die Route. Ein Guide liefert Geschichte, Kontext und Gespräch. Manche Reisen brauchen beides jeden Tag, andere nur einen Fahrer auf den langen Etappen und lokale Führungen in den Städten. Wir empfehlen die schlankste Lösung, die zu Ihren Erwartungen passt.',
  },
  options: {
    label: 'Vier sinnvolle Modelle',
    title: 'Vom reinen Transfer bis zur vollständig begleiteten Rundreise.',
    intro: 'Die Entscheidung muss nicht für alle Tage gleich sein. Eine gute Route wechselt das Unterstützungsniveau dort, wo es sinnvoll ist.',
    cards: [
      { number: '01', title: 'Fahrer für die gesamte Route', meta: 'Ein Fahrzeug · mehrere Reisetage', body: 'Der Fahrer begleitet Ihre Ortswechsel, kennt den Tagesplan und wartet an vereinbarten Stopps. Stadtführungen oder Museumsbesuche buchen wir bei Bedarf separat.' },
      { number: '02', title: 'Fahrer und deutschsprachiger Guide', meta: 'Komfort plus durchgehende Einordnung', body: 'Ideal, wenn Sie unterwegs viel erfahren möchten oder als Gruppe reisen. Der Guide kann sich auf Sie konzentrieren, während der Fahrer Verkehr und Fahrzeug übernimmt.' },
      { number: '03', title: 'Fahrer an Transfertagen', meta: 'Weniger Begleitung · mehr Zeit für sich', body: 'Sie werden zwischen den Orten gefahren und verbringen freie Tage unabhängig. Lokale Guides kommen nur in Tirana, Berat, Gjirokastra oder anderen ausgewählten Stationen hinzu.' },
      { number: '04', title: 'Geführter Start, Mietwagen danach', meta: 'Sicherheit am Anfang · Freiheit im zweiten Teil', body: 'Fahrer und Guide übernehmen die ersten Tage. An einem geeigneten Ort wechseln Sie in einen Mietwagen und setzen die vorbereitete Route selbstständig fort.' },
    ],
  },
  ideas: {
    label: 'Routen, die mit Fahrer gut funktionieren',
    title: 'Weniger tägliche Reibung, mehr Spielraum für gute Stopps.',
    intro: 'Die Beispiele zeigen einen Rhythmus, keine starren Pakete. Fahrzeiten und Übernachtungen werden für Ihre Saison, Flüge und gewünschte Tageslänge neu gerechnet.',
    cards: [
      { eyebrow: '7 Tage · kompakt', title: 'Die klassische Südrunde', line: 'Tirana · Berat · Gjirokastra · Riviera', body: 'Eine erste Albanienreise mit mehreren Orten, aber ohne jeden Tag das Hotel zu wechseln. Ein Fahrer ist besonders angenehm auf der Küstenstraße und bei den Übergängen zwischen Altstädten.', image: '/photos/gjirokaster.jpeg', alt: 'Handwerks- und Souvenirladen in der Altstadt von Gjirokastra', href: '/de/albanien-rundreise-7-tage', cta: '7-Tage-Route ansehen' },
      { eyebrow: '10 Tage · ausgewogen', title: 'Norden, Geschichte und Küste', line: 'Tirana · Shkodra · Berat · Gjirokastra · Riviera', body: 'Mehr Raum für Unterschiede zwischen Nord und Süd. Mit Fahrer lassen sich Zwischenstopps einbauen, ohne dass jemand aus Ihrer Gruppe den ganzen Tag konzentriert fahren muss.', image: '/photos/shiroke.jpeg', alt: 'Reisegruppe am Shkodra-See', href: '/de/albanien-rundreise-10-tage', cta: '10-Tage-Route ansehen' },
      { eyebrow: '14 Tage · mit Tiefe', title: 'Alpen bis Ionisches Meer', line: 'Shkodra · Valbona · Theth · Berat · Süden', body: 'Eine logistisch anspruchsvollere Route. In den Alpen kann das Fahrzeug- und Gepäckkonzept wechseln; genau hier ist saubere Koordination wichtiger als ein schönes Routendiagramm.', image: '/photos/valbone.jpeg', alt: 'Wandergruppe auf einem Bergweg bei Valbona', href: '/de/albanien-rundreise-14-tage', cta: '14-Tage-Route ansehen' },
    ],
  },
  details: {
    label: 'Was wir konkret planen',
    title: 'Das Fahrzeug ist nur ein Teil der Lösung.',
    intro: 'Eine gute Fahrerreise steht und fällt mit realistischen Tagen, eindeutigen Leistungen und der Frage, was passiert, wenn Route und Fahrzeug nicht durchgehend zusammenpassen.',
    items: [
      { title: 'Fahrzeug und Gepäck', body: 'Vier Erwachsene mit großen Koffern brauchen mehr Platz als vier Personen für einen Tagesausflug. Wir kalkulieren Sitzplätze, Gepäck, Straßenprofil und Gruppengröße gemeinsam.' },
      { title: 'Realistische Fahrtage', body: 'Entfernungen wirken auf der Karte kurz, können auf kurvigen oder städtischen Abschnitten aber Zeit kosten. Wir planen Pausen und Besuche so, dass ein Transfertag nicht heimlich zum Zwölfstundentag wird.' },
      { title: 'Abholung und Ende', body: 'Flughafen, Hotel, Hafen oder Mietwagenstation: Start und Rückgabe werden schriftlich festgehalten. Bei Gabelflügen prüfen wir, ob eine andere Endlogik besser ist als die Rückfahrt nach Tirana.' },
      { title: 'Guide-Leistungen', body: 'Im Vorschlag steht, ob der Fahrer nur fährt, zusätzlich einfache praktische Unterstützung gibt oder ob ein lizenzierter Guide die inhaltliche Begleitung übernimmt. Diese Rollen werden nicht vermischt verkauft.' },
      { title: 'Unterkunft und Auslagen des Teams', body: 'Bei mehrtägigen Reisen können Übernachtung, Verpflegung oder Rückfahrt des Fahrers anfallen. Diese Punkte werden vorher benannt und nicht während der Reise nachgereicht.' },
    ],
  },
  reality: {
    label: 'Die Straße in Albanien',
    title: 'Die Kilometerzahl erzählt nur die halbe Geschichte.',
    paragraphs: [
      'Zwischen Tirana und Berat ist eine andere Art von Fahrtag als zwischen Bergtälern, Küstenorten und einer Altstadt ohne direkte Hotelzufahrt. Baustellen, Sommerverkehr und Parken verändern den Rhythmus zusätzlich.',
      'Darum versprechen wir keine unrealistischen Tageslisten. Wir planen, was wirklich in den Tag passt, und nennen Alternativen, wenn eine gewünschte Schleife mehr Fahrzeit als Erlebnis produziert.',
    ],
    image: '/photos/lin.jpeg',
    imageAlt: 'Blick über Lin und den Ohridsee in Albanien',
    facts: [
      { term: 'Planungsprinzip', detail: 'Fahrtzeit plus Pausen, Besuche und Hotelzugang' },
      { term: 'Mögliche Ergänzung', detail: 'Deutschsprachiger Guide durchgehend oder lokal' },
    ],
    linkHref: '/de/deutschsprachiger-reiseleiter-albanien',
    linkLabel: 'Guide und Fahrer richtig kombinieren',
  },
  process: {
    label: 'So entsteht die Fahrerreise',
    title: 'Route, Fahrzeug und Menschen werden gemeinsam geplant.',
    steps: [
      { number: '01', title: 'Eckdaten schicken', meta: '', body: 'Reisedaten, Flüge, Gruppe, Gepäck und Orte, die Ihnen wichtig sind.' },
      { number: '02', title: 'Tage realistisch ordnen', meta: '', body: 'Wir prüfen Reihenfolge, Fahrzeiten und wo mehrere Nächte besser sind als tägliches Weiterziehen.' },
      { number: '03', title: 'Team und Leistungen festlegen', meta: '', body: 'Sie erhalten Fahrer, Fahrzeug, Guide-Tage, Ein- und Ausschlüsse sowie direkte Kosten klar aufgeführt.' },
      { number: '04', title: 'Abgeholt werden', meta: '', body: 'Der vereinbarte Fahrer kennt Route und Treffpunkt; Sie behalten einen lokalen Ansprechpartner.' },
    ],
  },
  pricing: {
    label: 'Was den Preis bestimmt',
    title: 'Fahrerpreise ohne Route sind nur scheinbar konkret.',
    body: 'Fahrzeugklasse, Einsatztage, Kilometer, notwendige Rückfahrten und Übernachtungen verändern den Preis. Ein Angebot für Ihre Route ist aussagekräftiger als ein niedriger Tagespreis, bei dem später Auslagen hinzukommen.',
    factorsLabel: 'Für eine belastbare Kalkulation',
    factors: ['Reisedaten und vollständige Strecke', 'Anzahl der Reisenden und Gepäck', 'Fahrer allein oder Fahrer plus Guide', 'Tage mit Bereitschaft, Transfers und freie Tage', 'Unterkunft, Maut, Parken und mögliche Rückfahrten'],
    promise: 'Wir trennen den Preis für Fahrzeug und Fahrer von Guide-Leistungen, Unterkünften und direkt bezahlten Ausgaben.',
    cta: 'Fahrerreise kalkulieren lassen',
  },
  faq: {
    label: 'Vor der Buchung',
    title: 'Fragen zur privaten Rundreise mit Fahrer.',
    intro: 'Schicken Sie uns Ihre Wunschroute auch dann, wenn sie noch zu voll ist. Das lässt sich leichter verbessern als ein Angebot ohne Strecke.',
    items: [
      { question: 'Was kostet ein privater Fahrer in Albanien?', answer: 'Das lässt sich seriös erst mit Route, Tagen, Gruppengröße und Fahrzeugbedarf sagen. Ein Flughafentransfer, ein Tagesausflug und eine zweiwöchige Rundreise haben unterschiedliche Kostenstrukturen. Sie erhalten ein aufgeschlüsseltes Angebot statt eines Lockpreises pro Tag.' },
      { question: 'Spricht der Fahrer Deutsch?', answer: 'Das hängt vom vorgeschlagenen Fahrer ab und wird vorab genannt. Wenn deutschsprachige Erklärungen und Gespräche wichtig sind, empfehlen wir einen separaten deutschsprachigen Guide. Der Fahrer muss dann nicht gleichzeitig zwei Berufe erfüllen.' },
      { question: 'Ist der Fahrer zugleich Reiseleiter?', answer: 'Nicht automatisch. Fahrer und Reiseleiter haben unterschiedliche Aufgaben. Im Angebot steht ausdrücklich, welche Rolle die vorgeschlagene Person übernimmt und ob an bestimmten Tagen ein lizenzierter Guide hinzukommt.' },
      { question: 'Kann der Fahrer mehrere Tage mit uns reisen?', answer: 'Ja. Bei einer mehrtägigen Begleitung berücksichtigen wir Arbeitsrhythmus, Unterbringung, Auslagen und gegebenenfalls die Rückfahrt des Fahrers. Diese Punkte werden vor der Bestätigung geklärt.' },
      { question: 'Können Kindersitze oder ein größeres Fahrzeug organisiert werden?', answer: 'Das kann je nach Verfügbarkeit berücksichtigt werden. Nennen Sie Alter der Kinder, gewünschte Sitzart, Personenzahl und Gepäck frühzeitig, damit das konkrete Fahrzeug passend angefragt wird.' },
      { question: 'Kann die Reise mit einem Mietwagen kombiniert werden?', answer: 'Ja. Ein häufig sinnvolles Modell ist ein geführter Start mit Fahrer und Guide, danach eine Mietwagenübergabe in einem geeigneten Ort. Die unabhängige Route wird so geplant, dass Rückgabe und Abflug zusammenpassen.' },
    ],
  },
  preInquiry: {
    label: 'Der beste erste Entwurf',
    title: 'Schicken Sie uns die Route, wie Sie sie gerade im Kopf haben.',
    body: 'Wir prüfen Tageslängen, Fahrzeugbedarf und sinnvolle Guide-Tage. Danach erhalten Sie eine klare Empfehlung, was vollständig mit Fahrer, punktuell begleitet oder selbst gefahren werden sollte.',
  },
};
