import type { SeoLandingPage } from './types';

export const deFamilyPage: SeoLandingPage = {
  locale: 'de',
  slug: 'albanien-mit-kindern',
  metaTitle: 'Albanien mit Kindern | Familienreise individuell planen',
  metaDescription: 'Albanien mit Kindern individuell bereisen: familiengerechte Rundreise, wenige Hotelwechsel, Küste, Kultur und private Guides für jedes Alter.',
  ogTitle: 'Albanien mit Kindern: eine Reise, die für alle funktioniert',
  breadcrumb: 'Albanien mit Kindern',
  serviceName: 'Individuelle Familienreise durch Albanien',
  serviceTypes: ['Albanien mit Kindern', 'Familienurlaub Albanien', 'Albanien Rundreise mit Kindern'],
  audience: 'Familien mit kleinen Kindern, Schulkindern und Teenagern',
  nav: { options: 'Reisearten', ideas: 'Routen', details: 'Familienplanung', questions: 'Fragen' },
  headerCta: 'Familienreise planen',
  hero: {
    eyebrow: 'Familienreise · privat · altersgerecht',
    title: 'Albanien mit Kindern, ohne jeden Tag alle zu überfordern.',
    lede: 'Eine private Familienreise mit wenigen guten Standorten, realistischen Fahrzeiten und Erlebnissen, die nicht nur für Erwachsene interessant sind. Wir planen für das jüngste Kind, die Teenager und die Eltern gleichzeitig.',
    primaryCta: 'Familienroute anfragen',
    secondaryCta: 'Reisearten ansehen',
    facts: ['Kleine Kinder bis Teenager', 'Fahrer oder Mietwagen', 'Tempo Ihrer Familie'],
    image: '/photos/karavasta.jpeg',
    imageAlt: 'Langer Holzsteg über die Lagune von Karavasta',
    imageCaption: 'Naturtage · Platz statt Programm',
    note: 'Mit Kindern ist der beste Reisetag selten der mit den meisten Sehenswürdigkeiten. Er ist der, an dem noch Energie für den Abend bleibt.',
  },
  promise: {
    label: 'Familienlogik statt Erwachsenenroute',
    title: 'Ein Fünfjähriger und zwei Teenager reisen nicht im selben Takt.',
    body: 'Darum setzen wir nicht einfach „kinderfreundlich“ vor eine klassische Rundreise. Wir prüfen, wie oft Sie Koffer packen, wann Fahrten stattfinden, wo ein Pool oder Strandtag wirklich hilft und welche Führung kurz genug ist, um neugierig zu bleiben.',
  },
  options: {
    label: 'Vier passende Reisearten',
    title: 'Die Familie entscheidet, wie viel Organisation abgegeben wird.',
    intro: 'Transport und Begleitung können sich im Verlauf ändern. Für manche Familien ist ein Fahrer Urlaub; andere möchten unbedingt selbstständig bleiben.',
    cards: [
      { number: '01', title: 'Mit privatem Fahrer', meta: 'Wenig Alltagslogistik für die Eltern', body: 'Niemand aus der Familie muss navigieren, parken oder nach einem langen Ausflug weiterfahren. Kindersitzbedarf, Gepäck und Fahrzeuggröße werden vorab geklärt.' },
      { number: '02', title: 'Als Selbstfahrerfamilie', meta: 'Flexibel bei Pausen und Tagesbeginn', body: 'Sie fahren im eigenen Rhythmus. Wir planen Strecken, Hotels mit praktikablem Zugang und Tage, an denen ein später Start nicht die ganze Route zerstört.' },
      { number: '03', title: 'Mit lokalen Guides', meta: 'Kurze, gute Führungen statt ganzer Vortragstage', body: 'In Tirana, Berat oder Gjirokastra treffen Sie einen Guide für einen klaren, altersgerechten Abschnitt. Danach geht es wieder zum Eis, Strand oder freien Nachmittag.' },
      { number: '04', title: 'Familienbesuch plus Urlaub', meta: 'Albanische Wurzeln · Verwandtschaft · neue Reise', body: 'Wenn Familienbesuche und Ferien zusammenkommen, bauen wir die privaten Termine in eine Route ein, statt sie als Störung eines fertigen Programms zu behandeln.' },
    ],
  },
  ideas: {
    label: 'Drei familiengerechte Formen',
    title: 'Weniger Umziehen, mehr echte Tage an einem Ort.',
    intro: 'Alter, Monat und Flugzeiten verändern die Auswahl. Die Beispiele zeigen bewusst unterschiedliche Tempi.',
    cards: [
      { eyebrow: '5–7 Tage', title: 'Tirana plus Küstenbasis', line: '1–2 Nächte Stadt · 4–5 Nächte am Meer', body: 'Gut für Familien, die Kultur und Strand verbinden möchten, ohne eine komplette Rundreise zu fahren. Von der Küstenbasis sind einzelne Ausflüge möglich; nicht jeder Tag braucht einen.', image: '/photos/zvernec.jpeg', alt: 'Holzsteg über das Wasser bei Zvërnec an der albanischen Küste', href: '#inquire', cta: 'Diese Reiseform besprechen' },
      { eyebrow: '8–10 Tage', title: 'Eine langsame Südrunde', line: 'Tirana · Berat · Gjirokastra · Küste', body: 'Zwei historische Städte, aber mit kurzen Führungen und mindestens einem Standort für mehrere Nächte. Der genaue Küstenort richtet sich nach Saison, gewünschtem Strand und Fahrlogik.', image: '/photos/berat.jpeg', alt: 'Altstadt von Berat als Station einer Familienreise', href: '/de/albanien-rundreise-10-tage', cta: '10-Tage-Idee ansehen' },
      { eyebrow: '12–14 Tage', title: 'Nord oder Süd vertiefen', line: 'Berge und See oder Kultur und Riviera', body: 'Zwei Wochen müssen nicht ganz Albanien enthalten. Mit kleineren Kindern ist oft eine regionale Vertiefung entspannter; mit aktiven Teenagern kann ein Bergmodul dazukommen.', image: '/photos/theth.jpeg', alt: 'Wandergruppe vor einem Wasserfall bei Theth', href: '/de/albanien-rundreise-14-tage', cta: '14-Tage-Idee anpassen' },
    ],
  },
  details: {
    label: 'Was Familien wirklich brauchen',
    title: 'Die kleinen Entscheidungen bestimmen, ob sich die Reise leicht anfühlt.',
    intro: 'Wir fragen nach Schlafrhythmus, Gepäck und Interessen, weil genau diese Dinge die richtige Route stärker verändern als eine allgemeine Top-Ten-Liste.',
    items: [
      { title: 'Alter und Energie', body: 'Ein Kind im Buggy, ein wanderfreudiges Schulkind und Teenager mit eigenen Interessen brauchen andere Tagesformen. Wir planen nicht nur nach der Anzahl der Reisenden.' },
      { title: 'Weniger Hotelwechsel', body: 'Mehrere Nächte an einem Ort schaffen Reserven für Hitze, Müdigkeit oder einen spontanen Strandtag. Tagesausflüge werden so gewählt, dass die Basis nicht zur täglichen langen Anfahrt wird.' },
      { title: 'Fahrzeug, Sitze und Gepäck', body: 'Kinderwagen, Koffer und Kindersitze verändern den Platzbedarf deutlich. Bedarf und Alter der Kinder werden bei einer Fahrer- oder Mietwagenanfrage von Anfang an angegeben.' },
      { title: 'Hitze und Tageszeit', body: 'Im Hochsommer liegen Stadtführungen besser am Morgen oder späteren Nachmittag. Die Mittagszeit kann für Fahrt, Pause oder Pool reserviert werden, statt für Kopfsteinpflaster ohne Schatten.' },
      { title: 'Etwas für jede Person', body: 'Geschichte für die Eltern, Bewegung für Kinder, Zeit allein für Teenager und kein erzwungenes Familienprogramm am Abend. Wir bauen Kontraste in die Reise ein.' },
    ],
  },
  reality: {
    label: 'Ein ehrlicher Familiencheck',
    title: 'Nicht jeder schöne Ort ist ein guter Familientag.',
    paragraphs: [
      'Eine Altstadt mit steilen Gassen kann faszinierend sein und mit Buggy gleichzeitig mühsam. Ein abgelegener Strand kann großartig aussehen und eine lange Zufahrt haben. Ein Bergtag kann Teenager begeistern, während ein kleines Kind eine andere Lösung braucht.',
      'Wir streichen solche Orte nicht automatisch. Wir erklären den Aufwand, bieten Varianten an und lassen Ihre Familie entscheiden. Gute Planung bedeutet, die Reibung sichtbar zu machen, bevor sie im Urlaub auftaucht.',
    ],
    image: '/photos/shiroke.jpeg',
    imageAlt: 'Private Reisegruppe bei einem entspannten Ausflug am See',
    facts: [
      { term: 'Gute Basis', detail: 'Mehrere Nächte · einfache Mahlzeiten · praktikabler Zugang' },
      { term: 'Guter Reisetag', detail: 'Ein Hauptpunkt · Pausen · Platz für spontane Änderungen' },
    ],
    linkHref: '/de/albanien-mietwagen-rundreise',
    linkLabel: 'Selbstfahrerreise für Familien prüfen',
  },
  process: {
    label: 'So planen wir für Familien',
    title: 'Wir beginnen bei den Menschen, nicht bei der Landkarte.',
    steps: [
      { number: '01', title: 'Familie beschreiben', meta: '', body: 'Alter, Interessen, Schlaf- oder Pausenbedarf, Gepäck und bisherige Reiseerfahrung.' },
      { number: '02', title: 'Reisetempo wählen', meta: '', body: 'Wir empfehlen Basen, Fahrtage und die richtige Mischung aus Kultur, Natur und freien Stunden.' },
      { number: '03', title: 'Transport und Guides festlegen', meta: '', body: 'Fahrer, Mietwagen, Sitze und kurze lokale Führungen werden passend zur Route abgestimmt.' },
      { number: '04', title: 'Mit Reserven reisen', meta: '', body: 'Der Plan enthält genug Struktur für Sicherheit und genug Luft, um einen müden Tag abzufangen.' },
    ],
  },
  pricing: {
    label: 'Familienangebot',
    title: 'Der Preis folgt dem Transport, den Nächten und der gewünschten Unterstützung.',
    body: 'Eine Familie im Mietwagen mit zwei lokalen Führungen braucht ein anderes Angebot als fünf Personen mit Fahrer und mehreren koordinierten Hotels. Wir zeigen die Bausteine getrennt, damit Sie sehen, wo Komfort kostet und wo Unabhängigkeit spart.',
    factorsLabel: 'Für die Kalkulation wichtig',
    factors: ['Alter und Anzahl der Kinder', 'Fahrer, Mietwagen oder Kombination', 'benötigte Kindersitze und Gepäckraum', 'Anzahl geführter Tage und Ausflüge', 'Umfang der Unterkunfts- und Buchungskoordination'],
    promise: 'Direkt bezahlte Hotels, Mietwagen und Eintritte werden von unserer Planungs- oder Guide-Leistung getrennt ausgewiesen.',
    cta: 'Familienangebot anfragen',
  },
  faq: {
    label: 'Mit Kindern unterwegs',
    title: 'Was Eltern vor einer Albanienreise fragen.',
    intro: 'Konkrete Sicherheits- und Einreisevorgaben prüfen Sie bitte zusätzlich bei offiziellen Stellen. Wir helfen mit der praktischen Route und lokalen Organisation.',
    items: [
      { question: 'Ist Albanien ein gutes Reiseziel mit Kindern?', answer: 'Für viele Familien ja: kurze Distanzen auf der Landkarte, abwechslungsreiche Landschaften, historische Städte und Küste lassen sich gut verbinden. Entscheidend ist, die tatsächlichen Fahrtzeiten und Hotelwechsel niedrig genug zu halten.' },
      { question: 'Welche Route eignet sich mit kleinen Kindern?', answer: 'Oft funktioniert Tirana plus eine historische Stadt und eine Küstenbasis besser als eine vollständige Nord-Süd-Runde. Je jünger die Kinder, desto wertvoller sind mehrere Nächte am selben Ort und ein einfacher Zugang zu Essen, Strand oder Pool.' },
      { question: 'Was können Teenager in Albanien unternehmen?', answer: 'Je nach Interessen können leichte Wanderungen, Kajak- oder Naturtage, Streetlife in Tirana, Burgen, Fotostopps und Strandzeit eingebaut werden. Wir fragen nach den Teenagern selbst, statt nur ein Kinderprogramm für alle vorzuschlagen.' },
      { question: 'Können Kindersitze organisiert werden?', answer: 'Bei einem privaten Fahrer oder einer Mietwagenkoordination kann der Bedarf angefragt werden. Bitte nennen Sie Alter, Größe und gewünschte Sitzart früh. Die konkrete Verfügbarkeit und Ausführung wird mit dem jeweiligen Anbieter bestätigt.' },
      { question: 'Brauchen wir einen privaten Fahrer?', answer: 'Nicht zwingend. Ein Fahrer entlastet Eltern bei Navigation, Parken und langen Übergängen. Ein Mietwagen gibt mehr Freiheit bei spontanen Pausen. Für manche Familien ist eine Kombination ideal: Fahrer am Anfang, Mietwagen für die ruhige Küstenphase.' },
      { question: 'Sind Stadtführungen für Kinder geeignet?', answer: 'Ja, wenn Dauer und Inhalt angepasst werden. Wir empfehlen kurze Abschnitte, konkrete Geschichten und Pausen. Ein dreistündiger Erwachsenenvortrag wird nicht dadurch kindgerecht, dass ein Eis am Ende versprochen wird.' },
      { question: 'Ist August mit Kindern zu heiß?', answer: 'August kann in Städten und an der Küste sehr heiß und voll sein. Frühere Startzeiten, längere Mittagspausen, wenige Ortswechsel und eine Unterkunft mit gutem Rückzugsort machen einen großen Unterschied. Für Ihre Daten passen wir den Tagesrhythmus an.' },
    ],
  },
  preInquiry: {
    label: 'Damit wir sinnvoll anfangen',
    title: 'Schreiben Sie das Alter der Kinder direkt in die erste Nachricht.',
    body: 'Dazu Reisedaten, Flüge, gewünschte Regionen und ob Sie selbst fahren möchten. Wir antworten mit einer Reiseform, die nicht voraussetzt, dass jeden Morgen alle dieselbe Energie haben.',
  },
};
