import type { SeoLandingPage } from './types';

export const deGuidePage: SeoLandingPage = {
  locale: 'de',
  slug: 'deutschsprachiger-reiseleiter-albanien',
  metaTitle: 'Deutschsprachiger Reiseleiter in Albanien | Arjes',
  metaDescription: 'Deutschsprachige Reiseleitung in Albanien für private Rundreisen, Tagesausflüge und Gruppen. Transparent vermittelt und passend zur Route ausgewählt.',
  ogTitle: 'Deutschsprachige Reiseleitung in Albanien, passend zu Ihrer Route',
  breadcrumb: 'Deutschsprachiger Reiseleiter Albanien',
  serviceName: 'Deutschsprachige Reiseleitung in Albanien',
  serviceTypes: ['Deutschsprachiger Reiseleiter Albanien', 'Private Reiseleitung Albanien', 'Lokale Guides Albanien'],
  audience: 'Deutschsprachige Individualreisende, Familien und private Gruppen',
  nav: { options: 'Modelle', ideas: 'Reiseformen', details: 'Auswahl', questions: 'Fragen' },
  headerCta: 'Guide anfragen',
  hero: {
    eyebrow: 'Deutschsprachig · privat · landesweit',
    title: 'Der passende Guide für Ihre Route – nicht einfach der nächste freie.',
    lede: 'Arjes begleitet ausgewählte Termine persönlich und stellt für andere Reisetage einen vertrauten deutschsprachigen Guide zusammen. Sie wissen vor der Buchung, wer Sie begleitet, welche Rolle diese Person übernimmt und wo ein Fahrer zusätzlich sinnvoll ist.',
    primaryCta: 'Reiseleitung anfragen',
    secondaryCta: 'Modelle ansehen',
    facts: ['Tagesausflug bis Rundreise', 'Guide, Fahrer oder beides', 'Name vor der Buchung'],
    image: '/photos/shiroke.jpeg',
    imageAlt: 'Deutschsprachige Reisegruppe mit Guide an einem See in Albanien',
    imageCaption: 'Unterwegs mit einer privaten Gruppe',
    note: 'Persönliche Reiseleitung bedeutet nicht, dass ein Name auf jeder Strecke gleich gut passt. Region, Gruppe und Reisetempo zählen.',
  },
  promise: {
    label: 'Was gute Reiseleitung leistet',
    title: 'Sie übersetzt mehr als Sprache.',
    body: 'Ein guter Guide kennt nicht nur Daten und Denkmäler. Er merkt, wann eine Gruppe noch eine Geschichte hören möchte, wann eine Pause wichtiger ist und wann ein ungeplanter Marktbesuch mehr erklärt als die nächste Sehenswürdigkeit. Genau deshalb wählen wir nach Route und Menschen aus.',
  },
  options: {
    label: 'Vier Modelle',
    title: 'So viel Begleitung, wie Ihre Reise tatsächlich braucht.',
    intro: 'Nicht jeder Tag gewinnt durch dauernde Reiseleitung. Oft ist eine kluge Kombination persönlicher und günstiger.',
    cards: [
      { number: '01', title: 'Arjes persönlich', meta: 'Ausgewählte Nachmittage und Wochenenden', body: 'Passend für Tirana, kurze Ausflüge und Termine, die in ihren Kalender fallen. Wir bestätigen persönliche Verfügbarkeit ausdrücklich; sie wird nie stillschweigend vorausgesetzt.' },
      { number: '02', title: 'Ein vertrauter deutschsprachiger Guide', meta: 'Andere Termine, Regionen und längere Reisen', body: 'Arjes schlägt eine lizenzierte Kollegin oder einen Kollegen vor, der zur Route und Gruppe passt. Sie erhalten den Namen und die geplante Rolle vor Ihrer Zusage.' },
      { number: '03', title: 'Guide plus privater Fahrer', meta: 'Mehrere Reisetage und häufige Ortswechsel', body: 'Der Guide bleibt bei der Gruppe, während der Fahrer Straße, Parken und Fahrzeug übernimmt. Das schafft Ruhe und lässt die Reiseleitung auch unterwegs arbeiten.' },
      { number: '04', title: 'Lokale Guides an wichtigen Orten', meta: 'Selbstfahrer oder Fahrerreise mit punktueller Tiefe', body: 'Sie reisen eigenständig und treffen in Tirana, Berat, Gjirokastra oder einer anderen Region jeweils die passende Person. Dazwischen gehört der Tag wieder Ihnen.' },
    ],
  },
  ideas: {
    label: 'Typische Einsätze',
    title: 'Drei Reisen, drei verschiedene Aufgaben für einen Guide.',
    intro: 'Das Reiseprogramm bestimmt die Rolle. Eine Stadtführung, eine Familienrundreise und eine fachlich interessierte Gruppe brauchen unterschiedliche Vorbereitung.',
    cards: [
      { eyebrow: '2–4 Stunden', title: 'Tirana im Gespräch', line: 'Geschichte · Alltag · Stadtentwicklung', body: 'Eine private Stadtführung auf Deutsch mit Zeit für Fragen und einem Treffpunkt im Zentrum. Für Paare genauso sinnvoll wie für Kollegien und kleine Gruppen.', image: '/photos/bektashi.jpeg', alt: 'Religiöse Architektur in Tirana', href: '/de/stadtfuehrung-tirana-deutsch', cta: 'Stadtführung in Tirana ansehen' },
      { eyebrow: '7–14 Tage', title: 'Eine Reise, ein roter Faden', line: 'Tirana · historische Städte · Berge oder Küste', body: 'Bei einer durchgehenden Reiseleitung entstehen Zusammenhänge zwischen Regionen und Tagen. Die Route wird nicht jeden Morgen neu erklärt, sondern entwickelt sich mit der Gruppe.', image: '/photos/gjirokaster-pov.jpeg', alt: 'Steindächer von Gjirokastra in Albanien', href: '/de/albanien-rundreise', cta: 'Rundreisen vergleichen' },
      { eyebrow: 'Einzelne Reisetage', title: 'Tiefe nur dort, wo sie zählt', line: 'Selbst fahren · lokal geführt werden', body: 'Eine gute Lösung für unabhängige Reisende: Mietwagen zwischen den Orten, deutschsprachige Führung an ausgewählten Stationen und ein lokaler Plan für die Übergänge.', image: '/photos/vjosa.jpeg', alt: 'Der Fluss Vjosa und die Berglandschaft im Süden Albaniens', href: '/de/albanien-mietwagen-rundreise', cta: 'Selbstfahrerreise planen' },
    ],
  },
  details: {
    label: 'Wie wir auswählen',
    title: 'Eine Guide-Vermittlung braucht mehr als einen Kalenderabgleich.',
    intro: 'Wir fragen kurz nach, bevor wir jemanden vorschlagen. So bleibt die Person nicht austauschbar und Ihre Erwartung realistisch.',
    items: [
      { title: 'Route und Region', body: 'Ein Guide mit starker Tirana-Erfahrung ist nicht automatisch die beste Begleitung für eine Wanderetappe oder eine kulturhistorische Reise im Süden. Wir wählen nach dem tatsächlichen Verlauf.' },
      { title: 'Deutsch, das im Gespräch funktioniert', body: 'Für private Reisen reicht auswendig gelerntes Vokabular nicht. Der Guide muss Fragen verstehen, Nuancen erklären und auch bei spontanen Themen sicher kommunizieren können.' },
      { title: 'Die Art Ihrer Gruppe', body: 'Familie mit Kindern, zwölf Arbeitskollegen und ein historisch versiertes Paar haben andere Bedürfnisse. Alter, Gruppengröße, Interessen und gewünschtes Tempo fließen in den Vorschlag ein.' },
      { title: 'Klare Rollen', body: 'Guide und Fahrer sind zwei verschiedene Aufgaben. Manchmal kann eine Person beides sinnvoll verbinden, oft ist die Trennung besser. Im Angebot steht, wer führt, wer fährt und an welchen Tagen.' },
      { title: 'Verfügbarkeit vor Bestätigung', body: 'Wir nennen keinen Wunschguide auf der Website und ersetzen ihn später unbemerkt. Der konkrete Vorschlag wird für Ihren Termin geprüft, bevor Sie sich festlegen.' },
    ],
  },
  reality: {
    label: 'Die ehrliche Antwort',
    title: 'Arjes ist nicht an jedem Tag in jedem Teil Albaniens.',
    paragraphs: [
      'Ausgewählte Stadtführungen, Nachmittage und Wochenenden führt Arjes selbst. Eine mehrwöchige Reise durch das ganze Land kann und soll aber nicht von einem einzigen Kalender abhängen.',
      'Darum arbeitet sie mit vertrauten lizenzierten Guides und sorgfältigen Fahrern. Ihre Aufgabe bleibt die Auswahl und Abstimmung: Sie bekommen keinen anonymen Subunternehmer, sondern einen konkreten Vorschlag mit klarer Verantwortung.',
    ],
    image: '/photos/theth.jpeg',
    imageAlt: 'Guide mit einer Gruppe an einem Wasserfall bei Theth',
    facts: [
      { term: 'Transparenz', detail: 'Name, Sprache und Aufgabe vor der Buchung' },
      { term: 'Mögliche Dauer', detail: 'Ein Stadtrundgang · ein Tagesausflug · mehrere Reisetage' },
    ],
    linkHref: '/de#about',
    linkLabel: 'Arjes und den Ansatz kennenlernen',
  },
  process: {
    label: 'Vom Bedarf zum Guide',
    title: 'Erst die Reise verstehen, dann die Person vorschlagen.',
    steps: [
      { number: '01', title: 'Reise grob beschreiben', meta: '', body: 'Daten, Route, Gruppengröße und die Tage, an denen Sie Begleitung wünschen.' },
      { number: '02', title: 'Rollen klären', meta: '', body: 'Wir besprechen, ob Sie Reiseleitung, Fahrer, lokale Führungen oder eine Kombination brauchen.' },
      { number: '03', title: 'Konkreten Vorschlag erhalten', meta: '', body: 'Sie erfahren, wer vorgesehen ist, welche Tage abgedeckt sind und was die Leistung kostet.' },
      { number: '04', title: 'Mit einem lokalen Kontakt reisen', meta: '', body: 'Guide und Fahrer kennen den Plan; Arjes bleibt für die abgestimmten Bausteine erreichbar.' },
    ],
  },
  pricing: {
    label: 'Preis der Reiseleitung',
    title: 'Ein Führungstag ist nicht dasselbe wie ein Reisetag mit Fahrzeug.',
    body: 'Der Preis hängt davon ab, ob ein Guide für zwei Stunden in Tirana, einen ganzen Ausflug oder mehrere Tage mit Übernachtungen gebucht wird. Fahrer, Fahrzeug, Eintritte und Unterkunft des Teams werden getrennt und verständlich ausgewiesen.',
    factorsLabel: 'Die wichtigsten Preisfaktoren',
    factors: ['Dauer und Anzahl der Einsatztage', 'Gruppengröße und gewünschte Sprache', 'Region und notwendige Anreise', 'Guide allein oder zusätzlich Fahrer und Fahrzeug', 'Übernachtungen und Auslagen auf einer Rundreise'],
    promise: 'Sie sehen vor der Zusage, welche Leistungen im Preis stecken und welche Kosten direkt bei Hotels, Museen oder anderen Partnern entstehen.',
    cta: 'Guide-Angebot anfragen',
  },
  faq: {
    label: 'Vor der Anfrage',
    title: 'Häufige Fragen zur deutschsprachigen Reiseleitung.',
    intro: 'Eine gute Anfrage muss noch keine fertige Route enthalten. Daten und eine grobe Idee reichen, um den nächsten Schritt vorzuschlagen.',
    items: [
      { question: 'Kann ich einen deutschsprachigen Reiseleiter für mehrere Tage buchen?', answer: 'Ja. Je nach Route kann ein Guide die gesamte Reise begleiten oder nur bestimmte Tage übernehmen. Bei langen Fahrstrecken empfehlen wir häufig einen zusätzlichen Fahrer, damit die Reiseleitung nicht gleichzeitig Navigation, Parken und Erklärungen bewältigen muss.' },
      { question: 'Wird Arjes unsere Reise persönlich begleiten?', answer: 'Wenn es sich um einen passenden Termin für eine ausgewählte Tirana-Tour, einen Nachmittag oder ein Wochenende handelt, ist das möglich. Für andere Daten und längere Reisen schlägt Arjes einen vertrauten deutschsprachigen Guide vor. Sie wissen vor der Buchung, wer geplant ist.' },
      { question: 'Sind die vermittelten Guides lizenziert?', answer: 'Für geführte Reisen arbeitet Arjes mit qualifizierten, lizenzierten Kolleginnen und Kollegen, die sie kennt und passend zur Aufgabe auswählt. Der konkrete Guide wird im Vorschlag benannt.' },
      { question: 'Brauchen wir neben dem Reiseleiter noch einen Fahrer?', answer: 'Nicht immer. Für eine Stadtführung oder lokale Tour reicht der Guide. Bei einer Rundreise mit vielen Fahrkilometern sorgt ein separater Fahrer meist für mehr Sicherheit, Ruhe und inhaltliche Qualität. Alternativ können Sie selbst fahren und lokale Guides treffen.' },
      { question: 'Können Sie auch eine Gruppe von zehn bis fünfzehn Personen begleiten?', answer: 'Ja, wenn Fahrzeug, Route und Führung darauf ausgelegt sind. Bitte nennen Sie die genaue Gruppengröße früh, weil Hörbarkeit, Gepäck, Sitzplätze und Pausen bei einer Gruppe anders geplant werden müssen als bei zwei Gästen.' },
      { question: 'Kann der Guide auch Hotels und Restaurants empfehlen?', answer: 'Ja. Empfehlungen können Teil der Routenplanung sein. Wir unterscheiden klar zwischen persönlicher Empfehlung, von uns koordinierter Reservierung und Leistungen, die Sie direkt beim jeweiligen Betrieb buchen und bezahlen.' },
    ],
  },
  preInquiry: {
    label: 'Was wir zuerst brauchen',
    title: 'Daten, Route, Gruppe und die Art von Begleitung.',
    body: 'Senden Sie auch eine unfertige Reiseskizze. Wir sagen Ihnen, an welchen Tagen ein deutschsprachiger Guide echten Mehrwert bringt und wo Fahrer oder Selbstfahrerzeit die bessere Lösung sind.',
  },
};
