import type { SeoLandingPage } from './types';

export const deSelfDrivePage: SeoLandingPage = {
  locale: 'de',
  slug: 'albanien-mietwagen-rundreise',
  metaTitle: 'Albanien-Rundreise mit Mietwagen | Individuell geplant',
  metaDescription: 'Individuelle Albanien-Rundreise mit Mietwagen: realistische Route, Hotel- und Parkplatzplanung, lokale Guides und geführter Start auf Wunsch.',
  ogTitle: 'Albanien mit dem Mietwagen: frei reisen, lokal geplant',
  breadcrumb: 'Albanien-Rundreise mit Mietwagen',
  serviceName: 'Individuelle Albanien-Rundreise mit Mietwagen',
  serviceTypes: ['Albanien Mietwagen Rundreise', 'Albanien Selbstfahrerreise', 'Geführter Start mit Mietwagenübergabe'],
  audience: 'Selbstfahrer, Paare und Familien, die Albanien individuell bereisen möchten',
  nav: { options: 'Reisemodelle', ideas: 'Routen', details: 'Planung', questions: 'Fragen' },
  headerCta: 'Route planen',
  hero: {
    eyebrow: 'Selbstfahrer · lokal geplant · flexibel',
    title: 'Albanien mit dem Mietwagen, ohne die Route unterwegs zu erfinden.',
    lede: 'Sie fahren selbst und behalten Ihre Freiheit. Wir bauen eine realistische Strecke, empfehlen passende Übernachtungsorte, koordinieren auf Wunsch die Mietwagenübergabe und setzen lokale Guides genau dort ein, wo sie den Tag besser machen.',
    primaryCta: 'Mietwagenreise anfragen',
    secondaryCta: 'Modelle vergleichen',
    facts: ['Eigene Route statt Paket', 'Geführter Start möglich', 'Lokaler Kontakt für den Plan'],
    image: '/photos/lin.jpeg',
    imageAlt: 'Blick über das Dorf Lin und den Ohridsee auf einer Albanien-Rundreise',
    imageCaption: 'Lin am Ohridsee · ein guter Zwischenstopp',
    note: 'Freiheit entsteht nicht durch möglichst viele Stopps. Sie entsteht, wenn die Route genug Luft lässt, um unterwegs anzuhalten.',
  },
  promise: {
    label: 'Was wir planen und was nicht',
    title: 'Wir verkaufen Ihnen nicht vor, dass jede Straße einfach und jeder Tag kurz ist.',
    body: 'Eine gute Selbstfahrerreise berücksichtigt kurvige Abschnitte, sommerlichen Verkehr, Parken an Altstädten, Gepäck und den Unterschied zwischen Kartenzeit und Reisetag. Sie erhalten eine Route mit begründeten Übernachtungen, nicht nur eine Liste schöner Orte.',
  },
  options: {
    label: 'Vier Wege zur Selbstfahrerreise',
    title: 'Komplett unabhängig oder mit lokaler Hilfe an den richtigen Stellen.',
    intro: 'Sie entscheiden, wie viel wir koordinieren. Auch eine einzelne Fahrzeugübergabe oder zwei lokale Führungen können eine lange Reise deutlich einfacher machen.',
    cards: [
      { number: '01', title: 'Route und Übernachtungslogik', meta: 'Sie buchen und fahren selbst', body: 'Wir ordnen Orte, Nächte und Tagesstrecken. Dazu kommen Hinweise, wo zentrale Lage wichtiger ist und wo ein Hotel mit gutem Fahrzeugzugang den Unterschied macht.' },
      { number: '02', title: 'Geführter Start in Tirana', meta: 'Ankommen, orientieren, dann losfahren', body: 'Ein Guide zeigt Ihnen Tirana und bespricht die erste Etappe. Der Mietwagen wird danach übernommen, sodass Sie Stadtverkehr und Parkplatzsuche am Ankunftstag vermeiden können.' },
      { number: '03', title: 'Guide und Fahrer zuerst, Mietwagen später', meta: 'Mehr Sicherheit in den ersten Tagen', body: 'Sie reisen zunächst begleitet und übernehmen das Auto in Korça, Përmet oder einem anderen geeigneten Ort. Die Rückgabe wird passend zum Abflug geplant.' },
      { number: '04', title: 'Lokale Guides unterwegs', meta: 'Frei fahren, vor Ort tiefer sehen', body: 'In ausgewählten Städten treffen Sie einen Guide für zwei oder drei Stunden. Dazwischen bestimmen Sie selbst, wann Sie starten, anhalten oder einen Programmpunkt auslassen.' },
    ],
  },
  ideas: {
    label: 'Drei brauchbare Routenformen',
    title: 'Die Strecke richtet sich nach Tagen und Jahreszeit, nicht nach einer Wunschliste.',
    intro: 'Jede dieser Routen kann gekürzt oder vertieft werden. Im Winter und in den Bergen braucht sie eine andere Logik als im Hochsommer.',
    cards: [
      { eyebrow: '7 Tage', title: 'Tirana und der Süden', line: 'Berat · Gjirokastra · Riviera · Tirana', body: 'Eine kompakte Runde mit Stadt, Geschichte und Küste. Sie funktioniert am besten, wenn nicht an jedem Küstenort eine zusätzliche Nacht erzwungen wird.', image: '/photos/berat.jpeg', alt: 'Historische Häuser in Berat', href: '/de/albanien-rundreise-7-tage', cta: '7-Tage-Route prüfen' },
      { eyebrow: '10 Tage', title: 'Nord und Süd verbinden', line: 'Shkodra · Berat · Gjirokastra · Ionische Küste', body: 'Ein ausgewogener erster Roadtrip. Zwei Nächte an ausgewählten Orten geben Zeit für Stadtführungen, Wanderungen oder einen Tag ohne Koffer.', image: '/photos/gjirokaster-pov.jpeg', alt: 'Blick über die Dächer von Gjirokastra', href: '/de/albanien-rundreise-10-tage', cta: '10-Tage-Route prüfen' },
      { eyebrow: '14 Tage', title: 'Alpen plus Südalbanien', line: 'Shkodra · Bergmodul · Berat · Süden · Küste', body: 'Machbar, aber nicht mit demselben Auto auf jedem Abschnitt. Fähre, Wanderung und Gepäcktransfer können eine gesonderte Nordlogik brauchen; danach beginnt der klassische Roadtrip.', image: '/photos/valbone.jpeg', alt: 'Wandergruppe auf einem felsigen Weg bei Valbona', href: '/de/albanien-rundreise-14-tage', cta: '14-Tage-Route prüfen' },
    ],
  },
  details: {
    label: 'Worauf die Planung achtet',
    title: 'Nicht nur von A nach B, sondern bis zum tatsächlichen Hotel.',
    intro: 'Selbstfahrerprobleme entstehen selten auf der großen Landkarte. Sie entstehen beim falschen Fahrzeug, an einer Altstadtzufahrt oder durch drei zu lange Tage hintereinander.',
    items: [
      { title: 'Übernahme und Rückgabe', body: 'Flughafen, Tirana-Zentrum oder eine andere Stadt können sinnvoll sein. Wir planen die Übergabe so, dass sie zur geführten Phase, ersten Etappe und Rückflugzeit passt.' },
      { title: 'Fahrzeug passend zur Route', body: 'Größe, Gepäckraum und Straßenprofil zählen mehr als die Kategoriebezeichnung im Angebot. Für manche Bergabschnitte ist eine andere Transportlösung klüger als ein größeres Auto für die ganze Reise.' },
      { title: 'Parken und Hotelzugang', body: 'Historische Zentren sind nicht überall direkt mit dem Auto erreichbar. Wir empfehlen Unterkünfte mit praktikabler Anfahrt oder erklären, wo das Fahrzeug bleibt und wie das Gepäck zum Hotel kommt.' },
      { title: 'Tageslänge und Pausen', body: 'Eine Fahrt von drei Stunden ist kein halber Tag, wenn Markt, Mittagessen, Aussichtspunkte und Check-in dazukommen. Wir schützen die Route vor mehreren überladenen Tagen hintereinander.' },
      { title: 'Plan B nach Saison', body: 'Bergstraßen, Fähren und touristische Angebote können saisonal anders funktionieren. Für Ihre Daten wird eine Alternative vorbereitet, statt eine Sommerroute ungeprüft auf den Winter zu übertragen.' },
    ],
  },
  reality: {
    label: 'Geführt starten, frei weiter',
    title: 'Die ersten Tage können den ganzen Roadtrip leichter machen.',
    paragraphs: [
      'Viele Reisende möchten Albanien selbst fahren, aber nicht direkt nach dem Flug mit Stadtverkehr, Fahrzeugübernahme und einer unbekannten Straße beginnen. Dann lohnt es sich, Tirana und die erste Region mit Guide oder Fahrer zu erleben.',
      'Das Auto kann später an einem vereinbarten Ort übernommen werden. Von dort folgt eine vorbereitete Strecke mit sinnvollen Nächten und klarer Rückgabe. Genau dieses Modell passt zu längeren Reisen, bei denen Begleitung nur am Anfang gewünscht ist.',
    ],
    image: '/photos/vjosa.jpeg',
    imageAlt: 'Weite Landschaft im Vjosa-Tal auf einer Mietwagenreise',
    facts: [
      { term: 'Beliebter Übergang', detail: 'Nach Tirana oder einer geführten Südost-Etappe' },
      { term: 'Mögliche Hilfe', detail: 'Route · Mietwagenübergabe · Hotels · lokale Guides' },
    ],
    linkHref: '/de/albanien-rundreise-mit-fahrer',
    linkLabel: 'Fahrer und Selbstfahrer vergleichen',
  },
  process: {
    label: 'Von den Flügen zur Route',
    title: 'Die Reise wird rückwärts vom echten Zeitrahmen geplant.',
    steps: [
      { number: '01', title: 'Flüge und Wünsche senden', meta: '', body: 'Ankunft, Abflug, Gruppe, Fahrererfahrung und Orte, die Sie wirklich sehen möchten.' },
      { number: '02', title: 'Route entschlacken', meta: '', body: 'Wir ordnen Nächte und Fahrtage und erklären offen, welche Schleife mehr kostet als sie bringt.' },
      { number: '03', title: 'Übergaben koordinieren', meta: '', body: 'Mietwagen, geführte Tage, lokale Guides und Unterkunftsempfehlungen werden zu einem Ablauf verbunden.' },
      { number: '04', title: 'Selbstständig losfahren', meta: '', body: 'Sie behalten Flexibilität und kennen gleichzeitig die Logik des nächsten Tages und Ihrer Rückgabe.' },
    ],
  },
  pricing: {
    label: 'Planung und Leistungen',
    title: 'Sie zahlen nur für die Hilfe, die Sie nutzen möchten.',
    body: 'Eine reine Routenberatung ist etwas anderes als eine Reise mit Guide-Tagen, Mietwagenkoordination, Transfers und mehreren Reservierungen. Wir definieren den Umfang vorab und unterscheiden unsere Leistung von Kosten, die Sie direkt beim Vermieter oder Hotel bezahlen.',
    factorsLabel: 'Was den Umfang bestimmt',
    factors: ['Länge und Komplexität der Route', 'reine Planung oder zusätzliche Buchungskoordination', 'Mietwagenübergabe außerhalb des Flughafens', 'Anzahl lokaler Führungen oder geführter Tage', 'Hotel- und Transferunterstützung'],
    promise: 'Im Angebot steht klar, welche Planung und Koordination wir übernehmen und welche Buchungen in Ihrem eigenen Namen erfolgen.',
    cta: 'Meine Selbstfahrerreise besprechen',
  },
  faq: {
    label: 'Praktisch unterwegs',
    title: 'Fragen zur Mietwagen-Rundreise in Albanien.',
    intro: 'Mietbedingungen und Straßensituationen können sich ändern. Konkrete Vorgaben prüfen wir für den Anbieter und Ihre Reisedaten, statt allgemeine Regeln als dauerhaft zu verkaufen.',
    items: [
      { question: 'Kann man Albanien gut mit dem Mietwagen bereisen?', answer: 'Ja, eine Mietwagenreise ist für viele Regionen sehr flexibel. Der entscheidende Punkt ist eine realistische Route. Stadtverkehr, Parken, kurvige Abschnitte und saisonale Bedingungen sollten in der Tagesplanung berücksichtigt werden.' },
      { question: 'Sollten wir den Mietwagen direkt am Flughafen übernehmen?', answer: 'Das kann praktisch sein, ist aber nicht immer die angenehmste Lösung. Wenn Sie zuerst Tirana zu Fuß erkunden oder einige Tage geführt reisen, kann eine spätere Übergabe im Zentrum oder in einer anderen Stadt besser passen. Verfügbarkeit und Einwegoptionen müssen konkret geprüft werden.' },
      { question: 'Brauchen wir einen Geländewagen?', answer: 'Nicht pauschal. Die richtige Fahrzeugwahl hängt von Route, Saison, Gepäck und den konkreten Zufahrten ab. Manche Bergmodule lassen sich besser mit lokalem Transfer oder Gepäcktransport lösen, statt für zwei Wochen ein größeres Fahrzeug zu mieten.' },
      { question: 'Können Sie einen Mietwagen in Korça oder Përmet übergeben lassen?', answer: 'Solche Übergaben können je nach Anbieter, Datum und Fahrzeug verfügbar sein. Wir prüfen die gewünschte Kombination und schlagen eine realistische Alternative vor, falls die exakte Stadt oder Einwegstrecke nicht sinnvoll angeboten wird.' },
      { question: 'Können wir unterwegs deutschsprachige Guides treffen?', answer: 'Ja. Lokale Führungen lassen sich an ausgewählten Orten in die Selbstfahrerroute einbauen. Sie erhalten Treffpunkt und Zeit vorab und fahren danach wieder unabhängig weiter.' },
      { question: 'Helfen Sie auch bei Hotels und Gästehäusern?', answer: 'Ja. Wir können Unterkünfte passend zu Route, Komfort und Parkplatzsituation empfehlen. Im Angebot steht, ob Sie selbst buchen, wir koordinieren oder Sie direkt mit dem Betrieb in Kontakt bringen.' },
      { question: 'Was passiert, wenn sich unterwegs etwas ändert?', answer: 'Bei privat geplanten Reisen lässt sich manches anpassen, aber Vermieter-, Hotel- und Guideverfügbarkeit setzen Grenzen. Für die von uns koordinierten Teile erhalten Sie einen lokalen Kontakt; Bedingungen des Mietvertrags und direkt gebuchter Leistungen gelten weiterhin.' },
    ],
  },
  preInquiry: {
    label: 'Für den ersten Vorschlag',
    title: 'Nennen Sie Flüge, Reisetage und fünf Orte, die Sie reizen.',
    body: 'Wir bauen daraus keine längere Liste, sondern eine fahrbare Reise. Wenn ein geführter Start oder eine spätere Mietwagenübergabe sinnvoll ist, sehen Sie das direkt im Vorschlag.',
  },
};
