import type { SeoLandingPage } from './types';

export const enDriverPage: SeoLandingPage = {
  locale: 'en',
  slug: 'albania-private-driver-tour',
  metaTitle: 'Private Driver in Albania | Custom Tours & Transfers',
  metaDescription: 'Hire a private driver in Albania for a custom multi-day tour, transfer or guided journey. Clear routes, suitable vehicles and local support.',
  ogTitle: 'Travel Albania with a private driver and a route that makes sense',
  breadcrumb: 'Albania private driver tour',
  serviceName: 'Private Driver Tours in Albania',
  serviceTypes: ['Private driver Albania', 'Albania tour with driver', 'Driver and guide Albania'],
  audience: 'Couples, families and small groups who prefer not to drive in Albania',
  nav: { options: 'Travel styles', ideas: 'Routes', details: 'What is planned', questions: 'Questions' },
  headerCta: 'Ask for a driver',
  hero: {
    eyebrow: 'Private vehicle · your route · local coordination',
    title: 'A private driver turns the road into part of the holiday.',
    lede: 'Travel between Tirana, the mountains, historic towns and the coast without making one member of your group responsible for traffic and parking. Add a local guide throughout, on selected days, or not at all.',
    primaryCta: 'Plan a driver itinerary',
    secondaryCta: 'Compare the options',
    facts: ['Private to your party', 'Vehicle matched to luggage', 'Guide available separately'],
    image: '/photos/vjosa.jpeg',
    imageAlt: 'The Vjosa river valley on a private road journey through Albania',
    imageCaption: 'Vjosa valley · southern Albania',
    note: 'A driver should remove logistics, not create a vague bundle. The route, vehicle, role and expenses need to be clear before the first pickup.',
  },
  promise: {
    label: 'Driver and guide are different jobs',
    title: 'Book each role for the value it adds.',
    body: 'A careful driver manages the vehicle, road and agreed timings. A guide interprets the places and stays in conversation with your group. Some journeys deserve both throughout. Others work better with a driver between towns and local guides only in Tirana, Berat or Gjirokastër.',
  },
  options: {
    label: 'Four ways to use a driver',
    title: 'From one difficult transfer to a complete private journey.',
    intro: 'The arrangement can change from day to day. We recommend the lightest version that still makes the trip easy.',
    cards: [
      { number: '01', title: 'Driver for the full route', meta: 'One vehicle · several days', body: 'The driver handles each transfer and follows the agreed itinerary. Guiding inside towns and sites is added only where you want it.' },
      { number: '02', title: 'Driver and private guide', meta: 'Comfort plus continuous context', body: 'The guide can focus on your group while the driver handles traffic, parking and the vehicle. Particularly useful for families and small groups.' },
      { number: '03', title: 'Driver on moving days', meta: 'Independent stays between transfers', body: 'Travel privately between bases, then keep whole days free. Meet a local guide for a specific city or museum rather than paying for full-time accompaniment.' },
      { number: '04', title: 'Guided start, rental car later', meta: 'Support first · independence afterwards', body: 'Begin with a driver and guide, collect a rental car in an agreed town and continue on a route designed around the return location and flight.' },
    ],
  },
  ideas: {
    label: 'Routes worth considering',
    title: 'Three journey shapes where a driver earns the fee.',
    intro: 'These are starting points. We recalculate nights and travel days for your flights, month and tolerance for time on the road.',
    cards: [
      { eyebrow: '7 days', title: 'The southern introduction', line: 'Tirana · Berat · Gjirokastër · Riviera', body: 'A compact first trip with several hotel approaches and a winding coastal section. A driver lets everyone enjoy the landscape and makes short stops easier.', image: '/photos/gjirokaster.jpeg', alt: 'Craft and souvenir shop in Gjirokastër old town', href: '/en/private-albania-tours', cta: 'Explore private journey styles' },
      { eyebrow: '10 days', title: 'North, heritage and coast', line: 'Tirana · Shkodra · Berat · south', body: 'Long enough to see regional contrast without moving every morning. The driver stays with the route; local guides can join only for the places that need interpretation.', image: '/photos/shiroke.jpeg', alt: 'A private group beside Lake Shkodra', href: '/en/albania-itinerary-10-days', cta: 'See the 10-day itinerary' },
      { eyebrow: '14 days', title: 'Alps to the Ionian Sea', line: 'Shkodra · mountain module · Berat · Riviera', body: 'The north can require transfers, luggage handling and a different vehicle pattern from the southern road trip. Good coordination matters more here than keeping one car at all costs.', image: '/photos/valbone.jpeg', alt: 'Walking group on a mountain trail near Valbona', href: '/en/albania-itinerary-14-days', cta: 'See the 14-day itinerary' },
    ],
  },
  details: {
    label: 'What the proposal should settle',
    title: 'A car and a daily rate are not yet a transport plan.',
    intro: 'The useful details are vehicle capacity, realistic hours, access to each hotel and what the driver is expected to do between pickups.',
    items: [
      { title: 'Vehicle and luggage', body: 'Passenger count alone is not enough. Large cases, pushchairs or walking equipment change the vehicle required, especially on an airport pickup with every bag on board.' },
      { title: 'Honest travel days', body: 'Map distances can hide bends, city traffic and slow hotel access. Stops, meals and visits are planned into the day rather than treated as free time outside the driving estimate.' },
      { title: 'Pickup and finish', body: 'Airport, hotel, port or rental desk are specified. If you are not flying in and out of Tirana, we examine the empty return and whether another ending makes better financial sense.' },
      { title: 'The driver’s role', body: 'We state whether the booking is transport only, includes practical assistance, or is paired with a licensed guide. Conversation in a shared language is not presented as a substitute for guiding.' },
      { title: 'Team costs on multi-day work', body: 'Driver accommodation, meals, parking and a return journey may apply. The proposal identifies these before you commit rather than adding them from the road.' },
    ],
  },
  reality: {
    label: 'A realistic day on the road',
    title: 'Short on the map does not always mean light in the diary.',
    paragraphs: [
      'A drive between two towns may also contain a market stop, lunch, a historic site and a hotel reached through narrow streets. Summer traffic and mountain weather can change the margin further.',
      'We would rather remove one weak stop than sell a route that reaches every hotel at dinner time. The driver receives the same agreed plan, so the pace is not renegotiated each morning.',
    ],
    image: '/photos/lin.jpeg',
    imageAlt: 'View over Lin and Lake Ohrid on an Albania driving route',
    facts: [
      { term: 'Built around', detail: 'Flights · luggage · actual hotel access · comfortable hours' },
      { term: 'Can include', detail: 'Airport pickup · local guides · rental-car handover' },
    ],
    linkHref: '/en/albania-self-drive-tour',
    linkLabel: 'Compare a self-drive journey',
  },
  process: {
    label: 'Planning the transport',
    title: 'Route first, then the right vehicle and team.',
    steps: [
      { number: '01', title: 'Send the outline', meta: '', body: 'Dates, flights, party, luggage and the places currently on your list.' },
      { number: '02', title: 'Test the road days', meta: '', body: 'We adjust order, nights and stops to keep the journey comfortable.' },
      { number: '03', title: 'Confirm roles and costs', meta: '', body: 'Driver, vehicle, guide days, inclusions and direct expenses are set out clearly.' },
      { number: '04', title: 'Meet the agreed driver', meta: '', body: 'The driver has the plan and pickup details; you retain one local organising contact.' },
    ],
  },
  pricing: {
    label: 'A route-based quote',
    title: 'The cheapest daily rate rarely tells you the final cost.',
    body: 'Vehicle size, distance, working pattern, empty returns and overnight expenses all matter. We price the actual itinerary and separate transport from guiding, hotels and costs paid directly.',
    factorsLabel: 'The quote depends on',
    factors: ['complete route and dates', 'passengers, luggage and vehicle size', 'driver only or driver plus guide', 'transfer days, waiting days and free days', 'overnights, parking and any return positioning'],
    promise: 'You receive a written scope showing what the driver covers, what is additional and which third-party costs remain direct.',
    cta: 'Request a driver quote',
  },
  faq: {
    label: 'Before hiring a driver',
    title: 'Practical questions about private transport in Albania.',
    intro: 'If you already have a rough itinerary, send it. We can usually identify the expensive or tiring sections quickly.',
    items: [
      { question: 'How much does a private driver in Albania cost?', answer: 'It depends on the route, number of days, vehicle, working hours and whether the driver must stay overnight or return empty. A transfer and a two-week journey cannot be compared by one honest daily price. We provide a route-specific quote.' },
      { question: 'Can I hire a driver for several days?', answer: 'Yes. Multi-day journeys are possible and can include airport pickup, each transfer and agreed stops. Accommodation, meals or return travel for the driver are clarified in advance.' },
      { question: 'Is the private driver also a tour guide?', answer: 'Not automatically. Driving and licensed guiding are separate roles. Your proposal states whether you are booking transport, practical assistance, or a separate guide as well.' },
      { question: 'Can the driver speak English or German?', answer: 'Language ability depends on the individual proposed and is confirmed before booking. If detailed interpretation matters, we recommend a guide in the required language rather than relying on the driver to provide a tour.' },
      { question: 'Can you provide child seats or a larger vehicle?', answer: 'We can request suitable equipment and capacity from the transport partner. Send the children’s ages, required seat type, exact passenger count and luggage early so the specific vehicle can be confirmed.' },
      { question: 'Can we switch from a driver to a rental car part-way through?', answer: 'Yes, subject to rental availability and one-way conditions. We can shape a guided first section, coordinate a handover in a suitable town and plan the independent route back to your departure point.' },
    ],
  },
  preInquiry: {
    label: 'The useful first message',
    title: 'Send the route as it exists today, even if it is too ambitious.',
    body: 'Include dates, flights, people and luggage. We will show where a driver adds value, where a guide belongs and where an independent day may be the better choice.',
  },
};
