import type { SeoLandingPage } from './types';

export const enItinerary10Page: SeoLandingPage = {
  locale: 'en',
  slug: 'albania-itinerary-10-days',
  metaTitle: 'Albania Itinerary: 10 Days from Tirana to the Riviera',
  metaDescription: 'A realistic 10-day Albania itinerary through Tirana, Shkodra, Berat, Gjirokastër and the Riviera. Customise it with a guide, driver or rental car.',
  ogTitle: 'A 10-day Albania itinerary with north, heritage and coast',
  breadcrumb: 'Albania itinerary: 10 days',
  serviceName: 'Custom 10-Day Albania Itinerary',
  serviceTypes: ['Albania itinerary 10 days', '10-day private Albania tour', 'Albania road trip 10 days'],
  audience: 'First-time Albania visitors, couples, families and small private groups',
  nav: { options: 'Travel styles', ideas: 'Route', details: 'Day by day', questions: 'Questions' },
  headerCta: 'Adapt this route',
  hero: {
    eyebrow: '10 days · north to south · private',
    title: 'Ten days in Albania, without losing half of them to check-in.',
    lede: 'Begin in Tirana, see northern Albania around Shkodra, slow down in Berat and Gjirokastër, then reach the Ionian coast before returning to the capital. Travel with a driver, self-drive, or combine guidance with independent days.',
    primaryCta: 'Adapt the 10-day route',
    secondaryCta: 'Choose a travel style',
    facts: ['Tirana round trip', 'North, UNESCO towns and coast', 'Four to five hotel bases'],
    image: '/photos/gjirokaster-pov.jpeg',
    imageAlt: 'Stone rooftops of Gjirokastër on a 10-day Albania itinerary',
    imageCaption: 'Gjirokastër · southern Albania',
    note: 'Ten days can show Albania’s range. It cannot show every saved pin well. The route works because it chooses a few places to stay.',
  },
  promise: {
    label: 'The route in one sentence',
    title: 'Tirana → Shkodra → Berat → Gjirokastër → Riviera → Tirana.',
    body: 'This is a broad first journey with one northern base and a measured move south. It avoids trying to force a full Albanian Alps crossing into the same ten days; that deserves more time or a different route.',
  },
  options: {
    label: 'Four ways to travel it',
    title: 'Keep the same backbone and change the level of support.',
    intro: 'The itinerary can be fully guided or almost entirely independent. The best choice depends on driving confidence, group size and how much context you want each day.',
    cards: [
      { number: '01', title: 'Private guide and driver', meta: 'The easiest complete version', body: 'A guide carries the story across regions while a driver handles every move. Best for groups, families or travellers who want conversation throughout.' },
      { number: '02', title: 'Private driver, local guides', meta: 'Comfort with quiet days', body: 'Keep one transport plan, but add guiding only in Tirana, Berat and Gjirokastër. The coast and unstructured afternoons remain your own.' },
      { number: '03', title: 'Self-drive', meta: 'Maximum independence', body: 'Collect the car after seeing Tirana on foot. We plan parking, hotel access and sensible driving days rather than leaving the route as a row of map pins.' },
      { number: '04', title: 'Guided start, self-drive south', meta: 'Local confidence before independence', body: 'Begin with Tirana and the north guided, then take a rental car for Berat, Gjirokastër and the coast. Return it around your flight.' },
    ],
  },
  ideas: {
    label: 'The three movements',
    title: 'City energy, inland history, then the sea.',
    intro: 'The route has contrast without demanding a new room every night. Exact bases change with season and the kind of coast you want.',
    cards: [
      { eyebrow: 'Days 1–3', title: 'Tirana and the north', line: 'Tirana · Shkodra · lake or mountain edge', body: 'Land, understand the capital, then move north. Use Shkodra as a base for the lake, local culture or a season-appropriate day towards the mountains.', image: '/photos/shiroke.jpeg', alt: 'A group beside Lake Shkodra in northern Albania', href: '/en/tirana-private-tour', cta: 'Start with a Tirana walk' },
      { eyebrow: 'Days 4–6', title: 'Berat and Gjirokastër', line: 'Ottoman-era quarters · castles · lived-in streets', body: 'Cross the country once, then slow down. Berat deserves more than a photograph; Gjirokastër is best with time to walk after the day visitors leave.', image: '/photos/berat.jpeg', alt: 'Historic hillside houses in Berat', href: '/en/private-albania-tours', cta: 'Discuss a private guide' },
      { eyebrow: 'Days 7–10', title: 'Butrint, coast and return', line: 'Archaeology · Ionian Sea · Llogara · Tirana', body: 'Reach the south, choose one coastal base and keep a full day without luggage. Return north on the coastal road with only the stops that fit your flight plan.', image: '/photos/zvernec.jpeg', alt: 'Wooden causeway across the water at Zvërnec', href: '/en/albania-private-driver-tour', cta: 'Price the route with a driver' },
    ],
  },
  details: {
    label: 'Day by day',
    title: 'A ten-day outline that still has evenings.',
    intro: 'This version assumes arrival and departure in Tirana. Flight times can turn day one or day ten into partial days, so we protect the essential visits in the middle.',
    items: [
      { title: 'Days 1–2 · Tirana to Shkodra', body: 'Arrive in Tirana and take a private walk through the centre and Blloku. On day two, travel north to Shkodra, leaving time for the city, Rozafa area or the lake rather than treating it only as a gateway.' },
      { title: 'Day 3 · A northern day from Shkodra', body: 'Choose according to season and energy: a deeper Shkodra day, Lake Shkodra countryside, or a carefully timed excursion towards Theth. A full Alps crossing does not fit comfortably here.' },
      { title: 'Days 4–5 · Berat', body: 'Travel south through central Albania and stay two nights. Walk Mangalem and Gorica, visit the castle quarter and leave space for food, a winery or simply a slower morning.' },
      { title: 'Days 6–8 · Gjirokastër, Butrint and the coast', body: 'Continue to Gjirokastër for its steep stone city and castle, then move through the archaeological south towards one Riviera base. Day eight stays free of check-out.' },
      { title: 'Days 9–10 · Coastal road and Tirana', body: 'Return via the Llogara direction with selected stops, not every beach. Spend the final night in or near Tirana unless the departure time supports a different ending; use day ten for the city, Dajti or departure.' },
    ],
  },
  reality: {
    label: 'What this route leaves out',
    title: 'Valbona and Theth are not a casual two-day detour.',
    paragraphs: [
      'The Albanian Alps can be the heart of a journey, but a ferry, valley transfer, hiking day and luggage plan need room. Adding all of that to Berat, Gjirokastër and the Riviera creates a trip dominated by movement.',
      'For ten days, choose either a northern Alps route or this broad north-to-south introduction. If you want both mountains and coast at a humane pace, the 14-day itinerary is the better starting point.',
    ],
    image: '/photos/valbone.jpeg',
    imageAlt: 'Walking group on a mountain trail near Valbona',
    facts: [
      { term: 'This route includes', detail: 'Shkodra and a northern day, not a full Alps traverse' },
      { term: 'For the Alps plus coast', detail: 'Allow about 14 days or simplify the south' },
    ],
    linkHref: '/en/albania-itinerary-14-days',
    linkLabel: 'See the 14-day itinerary',
  },
  process: {
    label: 'Making it yours',
    title: 'The route changes around flights, season and pace.',
    steps: [
      { number: '01', title: 'Send the real dates', meta: '', body: 'Arrival and departure times, group, luggage and any non-negotiable place.' },
      { number: '02', title: 'Choose the north', meta: '', body: 'We decide whether Shkodra, Theth or another northern focus best fits the month.' },
      { number: '03', title: 'Choose the travel style', meta: '', body: 'Guide, private driver, rental car or a handover between them is built into the same route.' },
      { number: '04', title: 'Receive one clear proposal', meta: '', body: 'Day order, people, transport, inclusions and direct costs are set out before confirmation.' },
    ],
  },
  pricing: {
    label: 'Pricing a 10-day journey',
    title: 'The route is fixed only after the travel style is clear.',
    body: 'Ten self-drive days with three local walks cost very differently from ten days with a guide, driver and vehicle. We quote the services you request and keep hotel, rental and direct supplier costs visible.',
    factorsLabel: 'The proposal reflects',
    factors: ['number and ages of travellers', 'self-drive, private driver or guide and driver', 'season and northern route choice', 'hotel and booking support required', 'airport transfers, entrances and special activities'],
    promise: 'You can see which parts create the cost and simplify the support without losing the route itself.',
    cta: 'Request a 10-day proposal',
  },
  faq: {
    label: 'Planning ten days',
    title: 'Questions about this Albania itinerary.',
    intro: 'The route is a strong first draft, not a package departure. We adjust it before discussing final availability or cost.',
    items: [
      { question: 'Is 10 days enough for Albania?', answer: 'Yes, for a broad first journey. Ten days can combine Tirana, one northern base, Berat, Gjirokastër and the coast if hotel changes are controlled. It is not enough for a full Alps traverse and a relaxed southern circuit together.' },
      { question: 'Should we include Theth in a 10-day itinerary?', answer: 'You can, but something else should shrink. A day excursion from Shkodra may work in suitable conditions, while a proper Theth and Valbona experience needs more nights and different logistics. We decide based on season and priorities.' },
      { question: 'How many nights should we spend on the Riviera?', answer: 'Usually at least two nights in one base so there is one full day without luggage. Travellers focused on beaches may take a third night and remove a northern or inland stop.' },
      { question: 'Can this be a self-drive itinerary?', answer: 'Yes. Collecting the car after central Tirana is often practical. We then plan parking, hotel access and return timing. Local guides can meet you in selected towns.' },
      { question: 'Can we travel with a private driver?', answer: 'Yes. A driver can cover the full route or only the moving days. Add a guide throughout or use local guides in Tirana, Berat and Gjirokastër.' },
      { question: 'Does this itinerary work outside summer?', answer: 'Yes, with changes. Historic towns, Tirana and food-led travel work well beyond summer. The northern day, coastal rhythm and daylight need to be designed for the actual month rather than copied from an August itinerary.' },
      { question: 'Can you book hotels as well?', answer: 'We can recommend and, depending on the agreed planning scope, help coordinate suitable hotels and guesthouses. Your proposal states what we arrange and what you book or pay directly.' },
    ],
  },
  preInquiry: {
    label: 'Turn the outline into your trip',
    title: 'Send your flights and tell us which part you would hate to lose.',
    body: 'We will adjust the ten days around that priority, then recommend the right mix of private guide, driver and independent travel.',
  },
};
