import type { SeoLandingPage } from './types';

export const enItinerary14Page: SeoLandingPage = {
  locale: 'en',
  slug: 'albania-itinerary-14-days',
  metaTitle: 'Albania Itinerary: 14 Days from the Alps to the Coast',
  metaDescription: 'A realistic 14-day Albania itinerary through Tirana, Shkodra, Valbona, Theth, Berat, Gjirokastër and the Riviera, with private or self-drive options.',
  ogTitle: 'A 14-day Albania itinerary from the Alps to the Ionian coast',
  breadcrumb: 'Albania itinerary: 14 days',
  serviceName: 'Custom 14-Day Albania Itinerary',
  serviceTypes: ['Albania itinerary 14 days', 'Two-week Albania tour', 'Albania Alps and Riviera itinerary'],
  audience: 'Couples, active families and small private groups planning two weeks in Albania',
  nav: { options: 'Versions', ideas: 'Route', details: 'Day by day', questions: 'Questions' },
  headerCta: 'Adapt this route',
  hero: {
    eyebrow: '14 days · Alps to coast · custom',
    title: 'Two weeks, from the Albanian Alps to the Ionian Sea.',
    lede: 'Cross the northern valleys, spend real time in Berat, then travel through Gjirokastër to the Ionian coast. The route can include the Valbona–Theth hike, a non-hiking mountain version or a seasonal alternative.',
    primaryCta: 'Adapt the 14-day route',
    secondaryCta: 'Compare route versions',
    facts: ['Northern mountain module', 'Two-night stays in key places', 'Driver, guide and self-drive options'],
    image: '/photos/valbone.jpeg',
    imageAlt: 'Walking group on a mountain trail near Valbona in the Albanian Alps',
    imageCaption: 'Valbona · Albanian Alps',
    note: 'Fourteen days do not need fourteen destinations. The extra week is valuable because several places finally get a second morning.',
  },
  promise: {
    label: 'The active version',
    title: 'Tirana → Shkodra → Valbona → Theth → Berat → Gjirokastër → Riviera.',
    body: 'This route uses the north as a proper journey rather than a day trip, then crosses to central and southern Albania. It is ambitious but balanced by two-night stays and a full coastal day. The mountain module is rebuilt when weather or hiking preference demands it.',
  },
  options: {
    label: 'Four versions of two weeks',
    title: 'The mountains decide the route more than the beaches do.',
    intro: 'Choose the north honestly. Hiking ability, luggage, weather and transport connections determine whether the Valbona–Theth crossing belongs in your trip.',
    cards: [
      { number: '01', title: 'The active Alps crossing', meta: 'Valbona · pass hike · Theth', body: 'For prepared walkers in suitable conditions. Vehicle and luggage do not simply follow across the pass, so transfers and baggage need their own plan.' },
      { number: '02', title: 'Mountains without the pass', meta: 'Valleys, viewpoints and shorter walks', body: 'Keep Valbona or Theth as a base and use vehicle transfers between accessible points. Better for mixed abilities, families or anyone who does not want a full crossing.' },
      { number: '03', title: 'Outside the mountain season', meta: 'Korçë, Përmet or a deeper cultural south', body: 'Replace uncertain high routes with towns, food, springs, lower walks and the Vjosa landscape. Two weeks still work beautifully without forcing a summer itinerary.' },
      { number: '04', title: 'Guided north, self-drive south', meta: 'Complex logistics first · freedom later', body: 'Use local transport, guide and luggage support through the north. Collect a rental car after Shkodra or farther south for Berat, Gjirokastër and the coast.' },
    ],
  },
  ideas: {
    label: 'The journey in three acts',
    title: 'Mountains first, stone cities next, salt water last.',
    intro: 'The order gives the difficult logistics their own space and finishes with a slower coast before the return to Tirana.',
    cards: [
      { eyebrow: 'Days 1–7', title: 'Tirana and the Albanian Alps', line: 'Shkodra · Koman direction · Valbona · Theth', body: 'Travel north after a day in the capital. Reach Valbona through the appropriate seasonal route, spend time in the valley, cross or transfer to Theth, then return to Shkodra without rushing straight south.', image: '/photos/theth.jpeg', alt: 'A group by a waterfall near Theth', href: '/en/tirana-private-tour', cta: 'Plan the Tirana opening' },
      { eyebrow: 'Days 8–10', title: 'Berat and Gjirokastër', line: 'Two nights in Berat · one in Gjirokastër', body: 'After the north, slow down in the historic centre of the country. Berat gets a complete day; Gjirokastër gets an evening after the steep streets become quieter.', image: '/photos/berat-bridge.jpeg', alt: 'Pedestrian bridge across the Osum towards Berat’s historic quarters', href: '/en/private-albania-tours', cta: 'Discuss private guiding' },
      { eyebrow: 'Days 11–14', title: 'Butrint and the Ionian coast', line: 'Archaeology · two coastal nights · Tirana', body: 'Travel through the deep south, choose one coastal base and keep one entire day free. Return north via the Llogara direction for the final night and flight.', image: '/photos/butrint.jpeg', alt: 'Ancient ruins at Butrint in southern Albania', href: '/en/albania-private-driver-tour', cta: 'Price the full route with a driver' },
    ],
  },
  details: {
    label: 'Day by day',
    title: 'Fourteen days with one demanding week and one slower week.',
    intro: 'The outline assumes a mountain season suitable for the active version. We do not confirm the crossing until current conditions and your ability are properly considered.',
    items: [
      { title: 'Days 1–2 · Tirana and Shkodra', body: 'Arrive in Tirana, take a private city walk and recover from the flight. On day two, move north to Shkodra for the old centre, lake landscape and the practical start of the mountain plan.' },
      { title: 'Days 3–4 · Into Valbona', body: 'Travel via the Koman direction or the best current alternative for your dates. Stay two nights in Valbona so the valley is more than an arrival point and the active day begins rested.' },
      { title: 'Days 5–7 · Theth and return to Shkodra', body: 'Cross the Valbona Pass on foot in the active version, with luggage moved separately, or transfer by road in the non-hiking version. Spend a second night around Theth before returning to Shkodra.' },
      { title: 'Days 8–10 · Berat and Gjirokastër', body: 'Make the long move into central Albania, then give Berat a full day without packing. Continue to Gjirokastër for the castle, stone houses and an evening in the old town.' },
      { title: 'Days 11–14 · Butrint, coast and Tirana', body: 'Travel through Butrint or another southern focus to one Riviera base for two nights. Use the full coastal day as you please, then return via the Llogara direction for a final Tirana night and departure.' },
    ],
  },
  reality: {
    label: 'The Valbona–Theth reality',
    title: 'It is a mountain crossing, not a scenic transfer between hotels.',
    paragraphs: [
      'The classic route involves sustained walking, ascent, uneven terrain and weather exposure. Your main luggage needs another way around, and the guide, transfer and accommodation plan must fit together.',
      'If the crossing does not suit every person, that does not ruin the north. A valley-based version can use shorter walks and road transfers, or the group can follow two coordinated plans for one day.',
    ],
    image: '/photos/theth.jpeg',
    imageAlt: 'Travellers in the mountain landscape near Theth',
    facts: [
      { term: 'Confirm only after', detail: 'Season · conditions · ability · luggage plan' },
      { term: 'Alternative', detail: 'One valley base · shorter walks · road transfer' },
    ],
    linkHref: '/en/albania-itinerary-10-days',
    linkLabel: 'Compare the lighter 10-day route',
  },
  process: {
    label: 'Customising two weeks',
    title: 'Decide the mountain version before booking the rest around it.',
    steps: [
      { number: '01', title: 'Share dates and ability', meta: '', body: 'Flights, ages, walking experience, luggage and what the north means to you.' },
      { number: '02', title: 'Choose the Alps module', meta: '', body: 'Crossing, valley-based route or seasonal replacement is decided first.' },
      { number: '03', title: 'Fit the south around it', meta: '', body: 'Berat, Gjirokastër and the coast are paced around the confirmed northern logistics.' },
      { number: '04', title: 'Choose support by section', meta: '', body: 'Guide, private driver, local transfers and rental car can each cover the part they suit best.' },
    ],
  },
  pricing: {
    label: 'Pricing two weeks',
    title: 'The northern logistics and travel style create the biggest difference.',
    body: 'A guided Alps crossing with luggage transfers, a driver and southern hotels is not priced like a self-drive circuit with one valley visit. We separate the modules so the cost is understandable and adjustable.',
    factorsLabel: 'The proposal reflects',
    factors: ['active crossing, non-hiking north or seasonal alternative', 'guide, driver and rental-car days', 'luggage transfer and northern transport', 'group size and room requirements', 'hotel, activity and booking support'],
    promise: 'The quote shows which services are ours, which partners you pay directly and which mountain elements remain subject to conditions.',
    cta: 'Request a 14-day proposal',
  },
  faq: {
    label: 'Planning two weeks',
    title: 'Questions about this 14-day Albania itinerary.',
    intro: 'The mountain week deserves the practical questions. Ask them before choosing non-refundable stays around it.',
    items: [
      { question: 'Is 14 days enough for northern and southern Albania?', answer: 'Yes, if the route is disciplined. Two weeks can combine a genuine northern module, Berat, Gjirokastër and the coast. It still benefits from two-night stays and should not add every possible detour.' },
      { question: 'Do we have to hike from Valbona to Theth?', answer: 'No. The crossing is only one version. You can base in one valley, use shorter walks and transfer by road, or replace the mountain module entirely outside the suitable season.' },
      { question: 'Can our luggage be moved while we hike?', answer: 'A separate luggage plan can be arranged for the active crossing, subject to route and partner availability. The exact handover, bag size and next accommodation must be agreed before the day.' },
      { question: 'Can families follow this itinerary?', answer: 'Yes, but the north must match the youngest traveller and the family’s walking experience. A non-hiking mountain version, private driver and fewer late arrivals often make the route much more enjoyable.' },
      { question: 'Can we self-drive the whole route?', answer: 'Much of the journey works as a road trip, but the classic pass crossing does not allow the rental car to follow you across. Northern transfers, parking or a guided module need their own solution. You can collect or resume a car after the mountains.' },
      { question: 'What should replace the Alps in winter?', answer: 'Depending on dates and interests, we can deepen Tirana and Shkodra or build a culture-and-food route through Korçë, Përmet, the Vjosa region and the southern historic towns. The exact version follows current access and weather.' },
      { question: 'Should we spend two or three nights on the coast?', answer: 'Two nights provide one full luggage-free day. Beach-focused travellers may prefer three and remove a stop elsewhere. Outside summer, an extra historic-town or countryside night may be more valuable than another coastal night.' },
    ],
  },
  preInquiry: {
    label: 'The first decision',
    title: 'Tell us what “the Alps” means to your group.',
    body: 'A full crossing, easy valley walks, scenery without hiking, or simply northern Albania. Once that is honest, the other seven days fall into place.',
  },
};
