import type { SeoLandingPage } from './types';

export const enSelfDrivePage: SeoLandingPage = {
  locale: 'en',
  slug: 'albania-self-drive-tour',
  metaTitle: 'Albania Road Trip & Self-Drive Tour | Planned Locally',
  metaDescription: 'Plan an Albania road trip with a realistic self-drive route, rental-car handover, hotel advice and local guides where they add value.',
  ogTitle: 'An Albania road trip with freedom and a route that works',
  breadcrumb: 'Albania self-drive tour',
  serviceName: 'Albania Self-Drive Tour Planning',
  serviceTypes: ['Albania road trip', 'Self-drive Albania', 'Guided start and rental-car handover'],
  audience: 'Independent travellers, couples and families planning an Albania road trip',
  nav: { options: 'Ways to travel', ideas: 'Road trips', details: 'Planning', questions: 'Questions' },
  headerCta: 'Plan my road trip',
  hero: {
    eyebrow: 'Self-drive · locally planned · independent',
    title: 'Your Albania road trip should leave room to stop the car.',
    lede: 'Drive independently on a route built around real travel days, sensible bases and your departure flight. Add a guided start, a rental-car delivery or local guides along the way without turning the trip into an escorted tour.',
    primaryCta: 'Build a self-drive route',
    secondaryCta: 'See the travel models',
    facts: ['Your car and pace', 'Rental handover possible', 'Local help where useful'],
    image: '/photos/lin.jpeg',
    imageAlt: 'Lin and Lake Ohrid on a scenic Albania road trip',
    imageCaption: 'Lin · the stops between the famous places',
    note: 'Independence is easier with fewer compulsory miles. A road trip needs slack for lunch, a viewpoint and the place you did not know existed.',
  },
  promise: {
    label: 'What local planning changes',
    title: 'A pin on a map is not yet a good overnight stop.',
    body: 'We look at the road into town, parking, luggage, seasonal access and what the next morning feels like. The result is not the longest possible list of Albania highlights. It is a route you can drive without spending the best part of each day watching the arrival time move backwards.',
  },
  options: {
    label: 'Four levels of support',
    title: 'Keep the wheel. Hand over the parts you do not want to solve.',
    intro: 'A self-drive trip can still include local expertise. Choose route planning only or connect several services into one handover.',
    cards: [
      { number: '01', title: 'A realistic route', meta: 'You book and drive independently', body: 'We shape the order, number of nights and travel days, with practical hotel-location and parking considerations built into the plan.' },
      { number: '02', title: 'Tirana first, car second', meta: 'Walk the capital before collecting', body: 'Start with a private Tirana tour, then take the rental car when you leave. It avoids paying to park a car you do not need in the centre.' },
      { number: '03', title: 'Guided first five nights', meta: 'Confidence and context at the start', body: 'Travel initially with a guide and driver, collect a rental car in Korçë, Përmet or another workable town, then continue south or back towards Tirana.' },
      { number: '04', title: 'Local guides on the route', meta: 'Drive alone, meet expertise by appointment', body: 'Book a focused walk in selected towns. Between meetings, the morning starts when you want and every roadside stop remains your decision.' },
    ],
  },
  ideas: {
    label: 'Road-trip shapes',
    title: 'Three routes that can be driven without treating Albania as a checklist.',
    intro: 'Flights, month and mountain plans alter every version. We use these as a starting structure, then remove what does not fit.',
    cards: [
      { eyebrow: '7 days · south', title: 'Heritage and the Ionian coast', line: 'Tirana · Berat · Gjirokastër · Riviera', body: 'A compact loop with strong contrasts. Two-night stops matter: otherwise the route becomes six check-ins joined by scenic roads.', image: '/photos/gjirokaster-pov.jpeg', alt: 'Stone rooftops in Gjirokastër on an Albania road trip', href: '/en/private-albania-tours', cta: 'Compare private travel styles' },
      { eyebrow: '10 days · balanced', title: 'North to south without rushing', line: 'Shkodra · Berat · Gjirokastër · coast', body: 'A good first road trip with enough time to see the country change. A guide can join in Tirana and the historic towns; the open-road days stay yours.', image: '/photos/shiroke.jpeg', alt: 'Private group beside Lake Shkodra in northern Albania', href: '/en/albania-itinerary-10-days', cta: 'Open the 10-day route' },
      { eyebrow: '14 days · full range', title: 'Mountains, inland towns and sea', line: 'Northern module · central Albania · Riviera', body: 'The mountain section may need a ferry, local transfer or luggage plan rather than one rental car throughout. The classic self-drive portion can begin after the north.', image: '/photos/theth.jpeg', alt: 'Mountain waterfall near Theth in northern Albania', href: '/en/albania-itinerary-14-days', cta: 'Open the 14-day route' },
    ],
  },
  details: {
    label: 'The practical route',
    title: 'Plan beyond the main road and all the way to the hotel door.',
    intro: 'The awkward moments are usually small: a pedestrian old town, nowhere to leave the car, an oversized vehicle or a rental return too close to the flight.',
    items: [
      { title: 'Collection and return', body: 'Airport pickup is not the only option. If the trip starts with Tirana or a guided section, a later collection can be easier. One-way availability and fees are checked for the actual rental request.' },
      { title: 'The right vehicle', body: 'The route, season and luggage decide more than the category name. A special mountain segment may be better handled by local transport than by renting a larger car for every day.' },
      { title: 'Parking and old-town access', body: 'Historic centres are not always reached at the hotel entrance. We favour workable access or explain the parking and luggage transfer before you arrive after dark.' },
      { title: 'Travel time with real stops', body: 'Lunch, a swim, a viewpoint and check-in belong inside the day. We avoid placing several long transitions back to back simply because Google can draw the line.' },
      { title: 'Seasonal alternatives', body: 'Mountain access, ferry patterns and coastal services can vary. The route for your dates includes a sensible alternative rather than assuming an August plan works all year.' },
    ],
  },
  reality: {
    label: 'The guided-to-independent handover',
    title: 'You do not have to choose between a guide and a road trip.',
    paragraphs: [
      'The first days can provide context and remove the steepest logistical learning curve. Explore Tirana and travel into one region with a guide and driver, then collect a rental car once you are rested and outside the capital.',
      'We connect the handover to the independent route and the final return. This works particularly well on a three-week visit where only the opening five nights need full support.',
    ],
    image: '/photos/vjosa.jpeg',
    imageAlt: 'The Vjosa valley on the independent section of an Albania journey',
    facts: [
      { term: 'A useful pattern', detail: 'Guided arrival · regional handover · self-drive finish' },
      { term: 'Can connect', detail: 'Guide · driver · rental partner · hotel recommendations' },
    ],
    linkHref: '/en/albania-private-driver-tour',
    linkLabel: 'Compare travelling with a driver',
  },
  process: {
    label: 'Building the trip',
    title: 'Start with the flights and work inward.',
    steps: [
      { number: '01', title: 'Send dates and wish list', meta: '', body: 'Flights, people, driving confidence and the places that currently feel essential.' },
      { number: '02', title: 'Set a humane pace', meta: '', body: 'We order the route, protect multi-night stays and explain which detour is not worth the road time.' },
      { number: '03', title: 'Join the moving parts', meta: '', body: 'Rental handover, guide days, transfers and hotel advice are fitted around one timeline.' },
      { number: '04', title: 'Drive independently', meta: '', body: 'You retain freedom while knowing the logic of the route and where the car must end up.' },
    ],
  },
  pricing: {
    label: 'Choose the planning scope',
    title: 'Pay for the local help you want, not an escorted package you do not.',
    body: 'A route review is different from coordinating a rental delivery, private guides and accommodation suggestions across three weeks. We agree the scope and show which costs are ours and which you pay directly to each supplier.',
    factorsLabel: 'The planning quote reflects',
    factors: ['trip length and route complexity', 'route design only or active coordination', 'non-standard rental collection or one-way return', 'number of guided days and transfers', 'hotel and local booking support'],
    promise: 'Rental charges, hotels and direct supplier payments remain clearly separate from planning and guiding fees.',
    cta: 'Discuss my self-drive trip',
  },
  faq: {
    label: 'Before taking the wheel',
    title: 'Questions about an Albania road trip.',
    intro: 'Rental terms and road conditions can change. We verify time-sensitive details for your dates and chosen supplier rather than turning old advice into a promise.',
    items: [
      { question: 'Is Albania suitable for a self-drive trip?', answer: 'Yes, many travellers value the flexibility. A comfortable trip needs realistic travel days, thought about parking and extra care around mountain or seasonal sections. The route matters more than trying to cover every region.' },
      { question: 'Should we rent the car at Tirana airport?', answer: 'It can be convenient, but if you are spending time in central Tirana first, collecting later may avoid parking and unused rental days. A guided opening section can also finish with a handover outside the capital.' },
      { question: 'Do we need a four-wheel-drive vehicle?', answer: 'Not for every Albania road trip. The answer depends on exact roads, season and accommodation access. Some northern modules are better solved with local transfers, a ferry or luggage support rather than keeping one specialist vehicle for the whole trip.' },
      { question: 'Can a rental car be delivered in Korçë or Përmet?', answer: 'It may be possible depending on supplier, date, vehicle and one-way terms. We check the actual request and suggest the closest workable handover if the preferred town is not practical.' },
      { question: 'Can we meet guides while travelling independently?', answer: 'Yes. Private city walks and site visits can be scheduled along the route. You drive to the agreed meeting point, spend a few hours with the guide and then continue independently.' },
      { question: 'Can you recommend hotels with parking?', answer: 'Yes. We consider access and parking alongside location and comfort. The proposal explains whether you book directly, we coordinate, or the property is simply a recommendation.' },
      { question: 'Can you plan a 21-day trip with only the first five nights guided?', answer: 'Yes. We can design the guided opening, a rental-car handover and the independent route back to Tirana. It is one of the clearest uses of a hybrid journey.' },
    ],
  },
  preInquiry: {
    label: 'Give us the rough version',
    title: 'Flights, number of days and the places you keep saving.',
    body: 'We will turn those pins into a route with breathing room and tell you where a guide, driver or rental handover genuinely improves the trip.',
  },
};
