import type { SeoLandingPage } from './types';

export const enTiranaPage: SeoLandingPage = {
  locale: 'en',
  slug: 'tirana-private-tour',
  metaTitle: 'Private Tirana Walking Tour with a Local Guide | Arjes',
  metaDescription: 'A private Tirana walking tour with a local guide: Skanderbeg Square, Blloku, communist history and an honest look at everyday Albania.',
  ogTitle: 'A private Tirana walking tour built around your questions',
  breadcrumb: 'Private Tirana walking tour',
  serviceName: 'Private Tirana Walking Tour',
  serviceTypes: ['Tirana walking tour', 'Private tour guide Tirana', 'Tirana city tour'],
  audience: 'Couples, families, friends and small private groups visiting Tirana',
  nav: { options: 'Tour lengths', ideas: 'The walk', details: 'Details', questions: 'Questions' },
  headerCta: 'Check a date',
  hero: {
    eyebrow: 'Private · on foot · led by a local',
    title: 'Tirana makes more sense when someone joins the dots.',
    lede: 'Walk from Skanderbeg Square to Blloku with a local guide who can explain the monuments, then talk about the city outside them: housing, work, faith, migration, coffee and the pace of change.',
    primaryCta: 'Ask about a private tour',
    secondaryCta: 'Compare tour lengths',
    facts: ['Usually 2–3 hours', 'Central hotel pickup possible', 'Only your group'],
    image: '/photos/bektashi.jpeg',
    imageAlt: 'Religious architecture in Tirana beneath a bright blue sky',
    imageCaption: 'Tirana · belief, politics and daily life',
    note: 'A private walk has a route, but it should still follow the conversation. Your questions are part of the plan.',
  },
  promise: {
    label: 'What the walk is for',
    title: 'See the capital. Leave with a way to read it.',
    body: 'Tirana can look chaotic on a first morning: Ottoman fragments, Fascist planning, communist symbolism and bright new towers all share a few streets. The walk gives that contrast a structure without pretending the city has one simple story.',
  },
  options: {
    label: 'Four useful versions',
    title: 'Choose a walk that fits the day you actually have.',
    intro: 'Opening hours, summer heat and your interests affect the route. We confirm what can comfortably fit before you book.',
    cards: [
      { number: '01', title: 'The first look', meta: '2 hours · central Tirana', body: 'A focused introduction from Skanderbeg Square through the government quarter to the Pyramid and Blloku. Best for an arrival afternoon or a short stay.' },
      { number: '02', title: 'The full city conversation', meta: '3 hours · our usual recommendation', body: 'Enough time for the New Bazaar, communist-era context and a proper discussion of the city today, without turning the walk into a race between landmarks.' },
      { number: '03', title: 'Walk plus Bunk’Art 2', meta: 'Half day · city and museum', body: 'A deeper version for travellers interested in surveillance, isolation and memory. The museum needs its own time; squeezing it into a two-hour walk short-changes both.' },
      { number: '04', title: 'A walk for your group', meta: 'Family · colleagues · friends', body: 'We adapt the stops, pace and depth for your people. A family with teenagers and a professional group of twelve should not receive the same delivery.' },
    ],
  },
  ideas: {
    label: 'The shape of the walk',
    title: 'Three Tiranas within a few kilometres.',
    intro: 'This is the usual narrative, not a fixed script. Your hotel, the time of day and the questions that emerge change the exact streets.',
    cards: [
      { eyebrow: 'Part 01 · the public stage', title: 'Skanderbeg Square', line: 'Mosque · clock tower · museum · opera', body: 'The square opens the big questions: empire, independence, religion and the way each political era has redesigned the centre to tell its own story.', image: '/photos/bektashi.jpeg', alt: 'A place of worship in Tirana', href: '#inquire', cta: 'Ask about this walk' },
      { eyebrow: 'Part 02 · power and memory', title: 'Boulevard to the Pyramid', line: 'Bunk’Art 2 · ministries · former leadership sites', body: 'We discuss dictatorship through lived experience as well as architecture: what control meant, how people remember it differently and why the city keeps remaking its symbols.', image: '/photos/durres-amphitheatre.jpeg', alt: 'Historic stone architecture in Albania', href: '/en/private-albania-tours', cta: 'Explore private Albania tours' },
      { eyebrow: 'Part 03 · the city now', title: 'Blloku', line: 'Former restricted quarter · cafés · new construction', body: 'Once closed to ordinary Albanians, Blloku now brings together nightlife, expensive property and the city’s outward-looking generation. It is the right place to talk about Tirana today.', image: '/photos/berat-bridge.jpeg', alt: 'Pedestrian bridge across the Osum towards the historic quarters of Berat', href: '/en/albania-itinerary-10-days', cta: 'Build Tirana into a longer trip' },
    ],
  },
  details: {
    label: 'Before we meet',
    title: 'Five details keep a simple walk genuinely simple.',
    intro: 'A short message is enough. We then confirm the meeting point, timing, guide and anything that changes the standard route.',
    items: [
      { title: 'Meeting point', body: 'Skanderbeg Square is easiest for most visitors. If your hotel is central, pickup may be possible by agreement. Groups receive one precise landmark rather than a vague corner of the square.' },
      { title: 'Your guide', body: 'Arjes leads selected afternoons, weekends and short city tours. If she is unavailable, she proposes a trusted local colleague. You know who is planned before confirming.' },
      { title: 'Museums and entrance fees', body: 'A full museum visit changes the timing. We confirm what is practical for your date and state clearly whether tickets are separate. Current opening arrangements are checked for the actual tour.' },
      { title: 'Pace and access', body: 'Central Tirana is walkable, but heat, kerbs and crowds can matter. Tell us about reduced mobility, a pushchair or anyone who needs regular seated breaks.' },
      { title: 'What you are curious about', body: 'Politics, religion, architecture, daily costs, education or modern migration: one useful prompt lets the guide prepare a walk that belongs to your group.' },
    ],
  },
  reality: {
    label: 'Who leads the tour?',
    title: 'Local and personal, without pretending one diary covers every date.',
    paragraphs: [
      'Arjes is a licensed national guide based in Tirana. She personally leads selected city walks, afternoons and weekend dates.',
      'For other times she matches the booking with a trusted local guide and remains the organising contact. There is no quiet substitution after you arrive: the proposed guide is named before you confirm.',
    ],
    image: '/photos/shiroke.jpeg',
    imageAlt: 'Arjes with a private group during a tour in Albania',
    facts: [
      { term: 'Languages', detail: 'English · German · Albanian · Turkish' },
      { term: 'Best for', detail: 'Couples · families · friends · small groups' },
    ],
    linkHref: '/en/private-albania-tours',
    linkLabel: 'Meet the wider local approach',
  },
  process: {
    label: 'Booking the walk',
    title: 'Four small steps, then meet in the city.',
    steps: [
      { number: '01', title: 'Send the date', meta: '', body: 'Include your preferred time, group size and central hotel if already booked.' },
      { number: '02', title: 'Share one interest', meta: '', body: 'Tell us what you most want to understand, or what you have already read.' },
      { number: '03', title: 'Receive a clear confirmation', meta: '', body: 'We confirm guide, duration, meeting point, group price and any separate entrance fees.' },
      { number: '04', title: 'Walk at your pace', meta: '', body: 'No strangers join the tour, and questions can change the emphasis as you go.' },
    ],
  },
  pricing: {
    label: 'A group price',
    title: 'The quote reflects the walk you ask us to deliver.',
    body: 'A two-hour walk for a couple and a half-day visit for twelve colleagues need different preparation and timing. We quote the private group as agreed and identify museum tickets or other costs separately.',
    factorsLabel: 'Tell us',
    factors: ['date and preferred start time', 'number and approximate ages of guests', 'two hours, three hours or a half day', 'any museum you want to enter', 'mobility, pace or meeting-point needs'],
    promise: 'The confirmation names the guide, the meeting point, the agreed duration and what is or is not included.',
    cta: 'Request a group quote',
  },
  faq: {
    label: 'Useful before booking',
    title: 'Questions about a Tirana walking tour.',
    intro: 'If you have an unusually specific interest, include it. Private tours are at their best when the guide has something real to prepare for.',
    items: [
      { question: 'How long should a Tirana walking tour be?', answer: 'Three hours is a comfortable first introduction. Two hours works for a focused central walk. If you want to visit Bunk’Art 2 properly, allow a half day so the museum does not consume the entire city tour.' },
      { question: 'Where does the tour start?', answer: 'Usually at a precise meeting point on Skanderbeg Square. A central hotel pickup may be possible by agreement. The finishing point is commonly in or near Blloku, but we can adjust it around your next plan.' },
      { question: 'Is this a private tour?', answer: 'Yes. The guide is booked for your party only; we do not add other travellers. That allows the pace and subject matter to change around your group.' },
      { question: 'Is Bunk’Art 2 included?', answer: 'Only when agreed. We can include historical context outside the museum on a standard walk. A full visit takes additional time, and current opening hours and ticket arrangements are checked for your date.' },
      { question: 'Will Arjes guide us personally?', answer: 'Arjes leads selected short tours, afternoons and weekend dates. If the timing does not fit, she proposes a trusted local guide and tells you who that is before you book.' },
      { question: 'Can the tour cover everyday life in Albania?', answer: 'Yes. Alongside history, the walk can cover work, housing, religion, family life, migration, traffic and the speed of change in Tirana. Tell us which topics matter to you.' },
      { question: 'Does the tour work for children or a larger group?', answer: 'Yes, with adjustment. We shorten explanations for younger children and choose stops where a larger party can hear. Share ages and exact group size when you enquire.' },
    ],
  },
  preInquiry: {
    label: 'Start with the essentials',
    title: 'A date, a time and the number of people are enough.',
    body: 'Add one thing you would like to understand about Tirana. We will reply with availability, the proposed guide, sensible duration and a clear private-group quote.',
  },
};
